import { getTokenValue } from "./getTokenValue";

export const buttons = {
  primary: {
      backgroundColor: getTokenValue("primary"),
      color: getTokenValue("white"),
      fontFamily: "Manrope, sans-serif",
      width: "100%",
      height: "48px",
      fontWeight: "bold",
      fontSize: "16px",
      lineHeight: "24px",
      borderRadius: "8px",
      cursor: "pointer",
    },
    secondary: {
      backgroundColor: getTokenValue("sand"),
      color: getTokenValue("lavender"),
      fontFamily: "Manrope, sans-serif",
      fontWeight: "bold",
      fontSize: "16px",
      padding: "12px 20px",
      borderRadius: "8px",
      border: `1px solid ${getTokenValue("sand-200-borders")}`,
      cursor: "pointer",
      maxWidth: "322px",
    },
    tertiary: {
      backgroundColor: "transparent",
      color: getTokenValue("lavender-500"),
      fontFamily: "Manrope, sans-serif",
      fontWeight: "bold",
      fontSize: "16px",
      width: "100%",
      textAlign: "center",
      border: "none",
      cursor: "pointer",
    },
    submitButton: {
      padding: "12px",
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
      gap: "8px",
      backgroundColor: getTokenValue("purple-600"),
      color: getTokenValue("white"),
      border: "none",
      borderRadius: "16px",
      cursor: "pointer",
      fontWeight: "500",
      marginTop: "8px",
      height: "48px",
      fontSize: "15px",
      letterSpacing: "0.5px",
      hover: {
        opacity: "0.9",
      },
    },
    oAuthButton: {
      flex: 1,
      border: `1px solid ${getTokenValue("sand-200-borders")} !important`,
      backgroundColor: `${getTokenValue("white")} !important`,
      color: `${getTokenValue("grey-900")} !important`,
      fontWeight: "500",
      borderRadius: "16px !important",
      height: "45px",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      padding: "0 16px !important",
      gap: "8px",
      fontSize: "14px",
      letterSpacing: "0.5px",
    },

//   oAuthButton: {
//     flex: "1 1 0",
//     height: "56px",
//     borderRadius: "28px",
//     border: "1px solid #E5E7EB",
//     backgroundColor: getTokenValue("white-500"),
//     color: getTokenValue("black-500"),
//     fontWeight: "500",
//     fontSize: "16px",
//     display: "flex",
//     alignItems: "center",
//     justifyContent: "center",
//     gap: "12px",
//     cursor: "pointer",
//     padding: "0 24px",
//     boxSizing: "border-box",
//     width: "100%",
//     maxWidth: "100%",
//     "@media (max-width: 768px)": {
//       height: "44px",
//       borderRadius: "24px",
//       fontSize: "14px",
//       padding: "0 16px",
//       gap: "8px"
//     }

  oAuthButton2: {
    flex: "1 1 0",
    height: "56px",
    borderRadius: "28px",
    border: "1px solid #E5E7EB",
    backgroundColor: getTokenValue("white-500"),
    color: getTokenValue("black-500"),
    fontWeight: "500",
    fontSize: "16px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "12px",
    cursor: "pointer",
    padding: "0 24px",
    boxSizing: "border-box",
    width: "100%",
    maxWidth: "100%",
    boxShadow: "0 1px 2px rgba(0, 0, 0, 0.05)",
    hover: {
      backgroundColor: getTokenValue("gray-200"),
    }
},
};
