/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: f7DE9y7qp46fyCw5nuY8f9
// Component: BIS-N7QZzUVV

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import Button2 from "../../Button2"; // plasmic-import: RjZcZb_kakG7/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: f7DE9y7qp46fyCw5nuY8f9/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: f7DE9y7qp46fyCw5nuY8f9/styleTokensProvider
import { _useStyleTokens as useStyleTokens_antd_5_hostless } from "../antd_5_hostless/PlasmicStyleTokensProvider"; // plasmic-import: ohDidvG9XsCeFumugENU3J/styleTokensProvider
import { _useStyleTokens as useStyleTokens_library_tailwind_3_4_number_tokens } from "../library_tailwind_3_4_number_tokens/PlasmicStyleTokensProvider"; // plasmic-import: 4vjRXvnb4XuY6J15w9oRcQ/styleTokensProvider
import { _useStyleTokens as useStyleTokens_plasmic_rich_components } from "../plasmic_rich_components/PlasmicStyleTokensProvider"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: f7DE9y7qp46fyCw5nuY8f9/projectcss
import sty from "./PlasmicMobileNavbarBottom.module.css"; // plasmic-import: BIS-N7QZzUVV/css

import GridFourIcon from "./icons/PlasmicIcon__GridFour"; // plasmic-import: KzAe7cfwmhYT/icon
import PictogramIcon from "./icons/PlasmicIcon__Pictogram"; // plasmic-import: KlZQiGxQTluF/icon
import HeartStraightIcon from "./icons/PlasmicIcon__HeartStraight"; // plasmic-import: 2A8amxR7FAse/icon
import EnvelopeSimple2Icon from "./icons/PlasmicIcon__EnvelopeSimple2"; // plasmic-import: 44ROc7g2Vqof/icon
import PhGearFillIcon from "./icons/PlasmicIcon__PhGearFill"; // plasmic-import: M0oN64eO6n3z/icon
import HeartStraight2Icon from "./icons/PlasmicIcon__HeartStraight2"; // plasmic-import: IaiER4CsTFaK/icon

createPlasmicElementProxy;

export type PlasmicMobileNavbarBottom__VariantMembers = {};
export type PlasmicMobileNavbarBottom__VariantsArgs = {};
type VariantPropType = keyof PlasmicMobileNavbarBottom__VariantsArgs;
export const PlasmicMobileNavbarBottom__VariantProps =
  new Array<VariantPropType>();

export type PlasmicMobileNavbarBottom__ArgsType = {};
type ArgPropType = keyof PlasmicMobileNavbarBottom__ArgsType;
export const PlasmicMobileNavbarBottom__ArgProps = new Array<ArgPropType>();

export type PlasmicMobileNavbarBottom__OverridesType = {
  mobileNavbarBottom?: Flex__<"nav">;
  frame1437253914?: Flex__<"a"> & Partial<LinkProps>;
  frame23?: Flex__<"div">;
  frame1437253915?: Flex__<"a"> & Partial<LinkProps>;
  frame24?: Flex__<"div">;
  frame1437253916?: Flex__<"a"> & Partial<LinkProps>;
  frame25?: Flex__<"div">;
};

export interface DefaultMobileNavbarBottomProps {
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicMobileNavbarBottom__RenderFunc(props: {
  variants: PlasmicMobileNavbarBottom__VariantsArgs;
  args: PlasmicMobileNavbarBottom__ArgsType;
  overrides: PlasmicMobileNavbarBottom__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = _useGlobalVariants();

  const styleTokensClassNames = _useStyleTokens();
  const styleTokensClassNames_antd_5_hostless =
    useStyleTokens_antd_5_hostless();
  const styleTokensClassNames_library_tailwind_3_4_number_tokens =
    useStyleTokens_library_tailwind_3_4_number_tokens();
  const styleTokensClassNames_plasmic_rich_components =
    useStyleTokens_plasmic_rich_components();

  return (
    (hasVariant(globalVariants, "screen", "mobileOnly") ? true : false) ? (
      <nav
        data-plasmic-name={"mobileNavbarBottom"}
        data-plasmic-override={overrides.mobileNavbarBottom}
        data-plasmic-root={true}
        data-plasmic-for-node={forNode}
        className={classNames(
          projectcss.all,
          projectcss.root_reset,
          projectcss.plasmic_default_styles,
          projectcss.plasmic_mixins,
          styleTokensClassNames,
          styleTokensClassNames_antd_5_hostless,
          styleTokensClassNames_library_tailwind_3_4_number_tokens,
          styleTokensClassNames_plasmic_rich_components,
          sty.mobileNavbarBottom
        )}
      >
        <Button2
          className={classNames("__wab_instance", sty.button2__nsRvc)}
          label={
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text___7Gko
              )}
            >
              {"candidatures"}
            </div>
          }
          onClick={async event => {
            const $steps = {};

            $steps["goToMesCandidatures"] = true
              ? (() => {
                  const actionArgs = { destination: `/candidatures` };
                  return (({ destination }) => {
                    if (
                      typeof destination === "string" &&
                      destination.startsWith("#")
                    ) {
                      document
                        .getElementById(destination.substr(1))
                        .scrollIntoView({ behavior: "smooth" });
                    } else {
                      __nextRouter?.push(destination);
                    }
                  })?.apply(null, [actionArgs]);
                })()
              : undefined;
            if (
              $steps["goToMesCandidatures"] != null &&
              typeof $steps["goToMesCandidatures"] === "object" &&
              typeof $steps["goToMesCandidatures"].then === "function"
            ) {
              $steps["goToMesCandidatures"] = await $steps[
                "goToMesCandidatures"
              ];
            }
          }}
          start={
            <GridFourIcon
              className={classNames(projectcss.all, sty.svg__wXNi)}
              role={"img"}
            />
          }
          type={(() => {
            try {
              return $ctx.pagePath === "/candidatures" ? "actif" : "";
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return [];
              }
              throw e;
            }
          })()}
        />

        <Button2
          className={classNames("__wab_instance", sty.button2__nY5Al)}
          label={
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__a6Bnn
              )}
            >
              {"annonces"}
            </div>
          }
          onClick={async event => {
            const $steps = {};

            $steps["goToMesAnnonces"] = true
              ? (() => {
                  const actionArgs = { destination: `/annonces` };
                  return (({ destination }) => {
                    if (
                      typeof destination === "string" &&
                      destination.startsWith("#")
                    ) {
                      document
                        .getElementById(destination.substr(1))
                        .scrollIntoView({ behavior: "smooth" });
                    } else {
                      __nextRouter?.push(destination);
                    }
                  })?.apply(null, [actionArgs]);
                })()
              : undefined;
            if (
              $steps["goToMesAnnonces"] != null &&
              typeof $steps["goToMesAnnonces"] === "object" &&
              typeof $steps["goToMesAnnonces"].then === "function"
            ) {
              $steps["goToMesAnnonces"] = await $steps["goToMesAnnonces"];
            }
          }}
          start={
            <HeartStraightIcon
              className={classNames(projectcss.all, sty.svg__uvhC5)}
              role={"img"}
            />
          }
          type={(() => {
            try {
              return $ctx.pagePath === "/annonces" ? "actif" : "";
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return [];
              }
              throw e;
            }
          })()}
        />

        <Button2
          className={classNames("__wab_instance", sty.button2__tln4Z)}
          label={
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text___93GTo
              )}
            >
              {"alertes"}
            </div>
          }
          onClick={async event => {
            const $steps = {};

            $steps["goToMesAlertes"] = true
              ? (() => {
                  const actionArgs = { destination: `/alertes` };
                  return (({ destination }) => {
                    if (
                      typeof destination === "string" &&
                      destination.startsWith("#")
                    ) {
                      document
                        .getElementById(destination.substr(1))
                        .scrollIntoView({ behavior: "smooth" });
                    } else {
                      __nextRouter?.push(destination);
                    }
                  })?.apply(null, [actionArgs]);
                })()
              : undefined;
            if (
              $steps["goToMesAlertes"] != null &&
              typeof $steps["goToMesAlertes"] === "object" &&
              typeof $steps["goToMesAlertes"].then === "function"
            ) {
              $steps["goToMesAlertes"] = await $steps["goToMesAlertes"];
            }
          }}
          start={
            <EnvelopeSimple2Icon
              className={classNames(projectcss.all, sty.svg__b2M12)}
              role={"img"}
            />
          }
          type={(() => {
            try {
              return $ctx.pagePath === "/alertes" ? "actif" : "";
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return [];
              }
              throw e;
            }
          })()}
        />

        <Button2
          className={classNames("__wab_instance", sty.button2__rBgXg)}
          label={
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__bwVuo
              )}
            >
              {"param\u00e8tres"}
            </div>
          }
          onClick={async event => {
            const $steps = {};

            $steps["goToParametresDeCompte"] = true
              ? (() => {
                  const actionArgs = { destination: `/parametres-candidat` };
                  return (({ destination }) => {
                    if (
                      typeof destination === "string" &&
                      destination.startsWith("#")
                    ) {
                      document
                        .getElementById(destination.substr(1))
                        .scrollIntoView({ behavior: "smooth" });
                    } else {
                      __nextRouter?.push(destination);
                    }
                  })?.apply(null, [actionArgs]);
                })()
              : undefined;
            if (
              $steps["goToParametresDeCompte"] != null &&
              typeof $steps["goToParametresDeCompte"] === "object" &&
              typeof $steps["goToParametresDeCompte"].then === "function"
            ) {
              $steps["goToParametresDeCompte"] = await $steps[
                "goToParametresDeCompte"
              ];
            }
          }}
          start={
            <PhGearFillIcon
              className={classNames(projectcss.all, sty.svg__kWnKa)}
              role={"img"}
            />
          }
          type={(() => {
            try {
              return $ctx.pagePath === "/parametres-candidat" ? "actif" : "";
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return [];
              }
              throw e;
            }
          })()}
        />

        <PlasmicLink__
          data-plasmic-name={"frame1437253914"}
          data-plasmic-override={overrides.frame1437253914}
          className={classNames(
            projectcss.all,
            projectcss.a,
            sty.frame1437253914
          )}
          component={Link}
          href={`/annonces`}
          platform={"nextjs"}
        >
          <div
            data-plasmic-name={"frame23"}
            data-plasmic-override={overrides.frame23}
            className={classNames(projectcss.all, sty.frame23)}
          />

          <HeartStraight2Icon
            className={classNames(projectcss.all, sty.svg__zcS5Q)}
            role={"img"}
          />

          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__lr7Vm
            )}
          >
            {"ANNONCES"}
          </div>
        </PlasmicLink__>
        <PlasmicLink__
          data-plasmic-name={"frame1437253915"}
          data-plasmic-override={overrides.frame1437253915}
          className={classNames(
            projectcss.all,
            projectcss.a,
            sty.frame1437253915
          )}
          component={Link}
          href={`/alertes`}
          platform={"nextjs"}
        >
          <div
            data-plasmic-name={"frame24"}
            data-plasmic-override={overrides.frame24}
            className={classNames(projectcss.all, sty.frame24)}
          />

          <EnvelopeSimple2Icon
            className={classNames(projectcss.all, sty.svg__nNeIg)}
            role={"img"}
          />

          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__snnRj
            )}
          >
            {"ALERTES"}
          </div>
        </PlasmicLink__>
        <PlasmicLink__
          data-plasmic-name={"frame1437253916"}
          data-plasmic-override={overrides.frame1437253916}
          className={classNames(
            projectcss.all,
            projectcss.a,
            sty.frame1437253916
          )}
          component={Link}
          href={"/parametres"}
          platform={"nextjs"}
        >
          <div
            data-plasmic-name={"frame25"}
            data-plasmic-override={overrides.frame25}
            className={classNames(projectcss.all, sty.frame25)}
          />

          <PhGearFillIcon
            className={classNames(projectcss.all, sty.svg___2DkPg)}
            role={"img"}
          />

          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__oaBrw
            )}
          >
            {"PARAM\u00c8TRES"}
          </div>
        </PlasmicLink__>
      </nav>
    ) : null
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  mobileNavbarBottom: [
    "mobileNavbarBottom",
    "frame1437253914",
    "frame23",
    "frame1437253915",
    "frame24",
    "frame1437253916",
    "frame25"
  ],
  frame1437253914: ["frame1437253914", "frame23"],
  frame23: ["frame23"],
  frame1437253915: ["frame1437253915", "frame24"],
  frame24: ["frame24"],
  frame1437253916: ["frame1437253916", "frame25"],
  frame25: ["frame25"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  mobileNavbarBottom: "nav";
  frame1437253914: "a";
  frame23: "div";
  frame1437253915: "a";
  frame24: "div";
  frame1437253916: "a";
  frame25: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicMobileNavbarBottom__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicMobileNavbarBottom__VariantsArgs;
    args?: PlasmicMobileNavbarBottom__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicMobileNavbarBottom__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicMobileNavbarBottom__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicMobileNavbarBottom__ArgProps,
          internalVariantPropNames: PlasmicMobileNavbarBottom__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicMobileNavbarBottom__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "mobileNavbarBottom") {
    func.displayName = "PlasmicMobileNavbarBottom";
  } else {
    func.displayName = `PlasmicMobileNavbarBottom.${nodeName}`;
  }
  return func;
}

export const PlasmicMobileNavbarBottom = Object.assign(
  // Top-level PlasmicMobileNavbarBottom renders the root element
  makeNodeComponent("mobileNavbarBottom"),
  {
    // Helper components rendering sub-elements
    frame1437253914: makeNodeComponent("frame1437253914"),
    frame23: makeNodeComponent("frame23"),
    frame1437253915: makeNodeComponent("frame1437253915"),
    frame24: makeNodeComponent("frame24"),
    frame1437253916: makeNodeComponent("frame1437253916"),
    frame25: makeNodeComponent("frame25"),

    // Metadata about props expected for PlasmicMobileNavbarBottom
    internalVariantProps: PlasmicMobileNavbarBottom__VariantProps,
    internalArgProps: PlasmicMobileNavbarBottom__ArgProps
  }
);

export default PlasmicMobileNavbarBottom;
/* prettier-ignore-end */
