/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: f7DE9y7qp46fyCw5nuY8f9
// Component: _xSIsI4MUaab

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import {
  executePlasmicDataOp,
  usePlasmicDataOp,
  usePlasmicInvalidate
} from "@plasmicapp/react-web/lib/data-sources";

import Sidebar2 from "../../Sidebar2"; // plasmic-import: RXqL3kdDrXwo/component
import { DataGrid } from "../../others/data_grid/data_grid"; // plasmic-import: o8vMrKl-wEva/codeComponent
import { Fetcher } from "@plasmicapp/react-web/lib/data-sources";

import { useScreenVariants as useScreenVariantshm8Nko4B5BDd } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: HM8Nko4B5BDd/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_library_tailwind_3_4_number_tokens_css from "../library_tailwind_3_4_number_tokens/plasmic.module.css"; // plasmic-import: 4vjRXvnb4XuY6J15w9oRcQ/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: f7DE9y7qp46fyCw5nuY8f9/projectcss
import sty from "./PlasmicCandidaturesEmployeur.module.css"; // plasmic-import: _xSIsI4MUaab/css

createPlasmicElementProxy;

export type PlasmicCandidaturesEmployeur__VariantMembers = {};
export type PlasmicCandidaturesEmployeur__VariantsArgs = {};
type VariantPropType = keyof PlasmicCandidaturesEmployeur__VariantsArgs;
export const PlasmicCandidaturesEmployeur__VariantProps =
  new Array<VariantPropType>();

export type PlasmicCandidaturesEmployeur__ArgsType = {};
type ArgPropType = keyof PlasmicCandidaturesEmployeur__ArgsType;
export const PlasmicCandidaturesEmployeur__ArgProps = new Array<ArgPropType>();

export type PlasmicCandidaturesEmployeur__OverridesType = {
  root?: Flex__<"div">;
  sidebar2?: Flex__<typeof Sidebar2>;
  main?: Flex__<"main">;
  freeBox?: Flex__<"div">;
  heading2?: Flex__<"div">;
  card2?: Flex__<"div">;
  applications?: Flex__<"div">;
  dataGrid?: Flex__<typeof DataGrid>;
};

export interface DefaultCandidaturesEmployeurProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicCandidaturesEmployeur__RenderFunc(props: {
  variants: PlasmicCandidaturesEmployeur__VariantsArgs;
  args: PlasmicCandidaturesEmployeur__ArgsType;
  overrides: PlasmicCandidaturesEmployeur__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  let [$queries, setDollarQueries] = React.useState<
    Record<string, ReturnType<typeof usePlasmicDataOp>>
  >({});

  const new$Queries: Record<string, ReturnType<typeof usePlasmicDataOp>> = {
    getJobapplicationsByJobOffers: usePlasmicDataOp(() => {
      return {
        sourceId: "kVSSe8ab4TtzwRPnTeEeUp",
        opId: "1e3dda04-b7b2-4657-a520-9d22389e3e32",
        userArgs: {
          query: [$ctx.params.job_id]
        },
        cacheKey: `plasmic.$.1e3dda04-b7b2-4657-a520-9d22389e3e32.$.`,
        invalidatedKeys: null,
        roleId: null
      };
    }),
    getCandidatures: usePlasmicDataOp(() => {
      return {
        sourceId: "kVSSe8ab4TtzwRPnTeEeUp",
        opId: "2f7b34e5-91d1-4f7a-abab-21d56504b2bb",
        userArgs: {
          filters: [$ctx.params.job_id]
        },
        cacheKey: `plasmic.$.2f7b34e5-91d1-4f7a-abab-21d56504b2bb.$.`,
        invalidatedKeys: null,
        roleId: null
      };
    })
  };
  if (Object.keys(new$Queries).some(k => new$Queries[k] !== $queries[k])) {
    setDollarQueries(new$Queries);

    $queries = new$Queries;
  }

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantshm8Nko4B5BDd()
  });

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            plasmic_library_tailwind_3_4_number_tokens_css.plasmic_tokens,
            plasmic_plasmic_rich_components_css.plasmic_tokens,
            sty.root
          )}
        >
          <Sidebar2
            data-plasmic-name={"sidebar2"}
            data-plasmic-override={overrides.sidebar2}
            className={classNames("__wab_instance", sty.sidebar2)}
          />

          <Stack__
            as={"main"}
            data-plasmic-name={"main"}
            data-plasmic-override={overrides.main}
            hasGap={true}
            className={classNames(projectcss.all, sty.main)}
          >
            <div
              data-plasmic-name={"freeBox"}
              data-plasmic-override={overrides.freeBox}
              className={classNames(projectcss.all, sty.freeBox)}
            >
              <div
                data-plasmic-name={"heading2"}
                data-plasmic-override={overrides.heading2}
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.heading2
                )}
              >
                {"Les candidatures"}
              </div>
            </div>
            <Stack__
              as={"div"}
              data-plasmic-name={"card2"}
              data-plasmic-override={overrides.card2}
              hasGap={true}
              className={classNames(projectcss.all, sty.card2)}
            >
              <div
                data-plasmic-name={"applications"}
                data-plasmic-override={overrides.applications}
                className={classNames(projectcss.all, sty.applications)}
              >
                <DataGrid
                  data-plasmic-name={"dataGrid"}
                  data-plasmic-override={overrides.dataGrid}
                  className={classNames("__wab_instance", sty.dataGrid)}
                  columnHeaders={{}}
                  columnLabels={{
                    nom_du_candidat: "Nom du candidat",
                    note: "Note",
                    cv_nom: "CV",
                    lm_nom: "Lettre de motivation",
                    date_de_candidature: "Postul\u00e9 le",
                    status: "Statut"
                  }}
                  columnStyles={{
                    profile_photo: {
                      isImage: true,
                      imageSize: { width: "32px", height: "32px" },
                      align: "center"
                    }
                  }}
                  currentPage={1}
                  emptyStateMessage={"Aucune donnée disponible"}
                  enableExport={false}
                  exportFormats={"csv"}
                  isLoading={false}
                  pageSize={10}
                  responsive={{
                    minWidth: "100%",
                    horizontalOverflow: "auto",
                    verticalOverflow: "auto",
                    stickyHeader: true,
                    compactOnMobile: true,
                    breakpoint: 768
                  }}
                  tasks={(() => {
                    try {
                      return $queries.getJobapplicationsByJobOffers.data;
                    } catch (e) {
                      if (
                        e instanceof TypeError ||
                        e?.plasmicType === "PlasmicUndefinedDataError"
                      ) {
                        return [];
                      }
                      throw e;
                    }
                  })()}
                  theme={(() => {
                    const __composite = {
                      headerBgColor: null,
                      rowBgColor: "#ffffff",
                      hoverBgColor: "#f9f5ff",
                      borderColor: "#d9cdbf",
                      textColor: null,
                      fontSize: "14px"
                    };
                    __composite["headerBgColor"] = "#E6E6E6";
                    __composite["textColor"] = "#666666";
                    return __composite;
                  })()}
                />
              </div>
            </Stack__>
          </Stack__>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "sidebar2",
    "main",
    "freeBox",
    "heading2",
    "card2",
    "applications",
    "dataGrid"
  ],
  sidebar2: ["sidebar2"],
  main: ["main", "freeBox", "heading2", "card2", "applications", "dataGrid"],
  freeBox: ["freeBox", "heading2"],
  heading2: ["heading2"],
  card2: ["card2", "applications", "dataGrid"],
  applications: ["applications", "dataGrid"],
  dataGrid: ["dataGrid"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  sidebar2: typeof Sidebar2;
  main: "main";
  freeBox: "div";
  heading2: "div";
  card2: "div";
  applications: "div";
  dataGrid: typeof DataGrid;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicCandidaturesEmployeur__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicCandidaturesEmployeur__VariantsArgs;
    args?: PlasmicCandidaturesEmployeur__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicCandidaturesEmployeur__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicCandidaturesEmployeur__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicCandidaturesEmployeur__ArgProps,
          internalVariantPropNames: PlasmicCandidaturesEmployeur__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicCandidaturesEmployeur__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicCandidaturesEmployeur";
  } else {
    func.displayName = `PlasmicCandidaturesEmployeur.${nodeName}`;
  }
  return func;
}

export const PlasmicCandidaturesEmployeur = Object.assign(
  // Top-level PlasmicCandidaturesEmployeur renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    sidebar2: makeNodeComponent("sidebar2"),
    main: makeNodeComponent("main"),
    freeBox: makeNodeComponent("freeBox"),
    heading2: makeNodeComponent("heading2"),
    card2: makeNodeComponent("card2"),
    applications: makeNodeComponent("applications"),
    dataGrid: makeNodeComponent("dataGrid"),

    // Metadata about props expected for PlasmicCandidaturesEmployeur
    internalVariantProps: PlasmicCandidaturesEmployeur__VariantProps,
    internalArgProps: PlasmicCandidaturesEmployeur__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicCandidaturesEmployeur;
/* prettier-ignore-end */
