/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: f7DE9y7qp46fyCw5nuY8f9
// Component: 0Dt9ei2n73Lz

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_library_tailwind_3_4_number_tokens_css from "../library_tailwind_3_4_number_tokens/plasmic.module.css"; // plasmic-import: 4vjRXvnb4XuY6J15w9oRcQ/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: f7DE9y7qp46fyCw5nuY8f9/projectcss
import sty from "./PlasmicBoutonVoirLesOffres.module.css"; // plasmic-import: 0Dt9ei2n73Lz/css

import GroupIcon from "./icons/PlasmicIcon__Group"; // plasmic-import: yIYn4o5HgDaM/icon

createPlasmicElementProxy;

export type PlasmicBoutonVoirLesOffres__VariantMembers = {};
export type PlasmicBoutonVoirLesOffres__VariantsArgs = {};
type VariantPropType = keyof PlasmicBoutonVoirLesOffres__VariantsArgs;
export const PlasmicBoutonVoirLesOffres__VariantProps =
  new Array<VariantPropType>();

export type PlasmicBoutonVoirLesOffres__ArgsType = {};
type ArgPropType = keyof PlasmicBoutonVoirLesOffres__ArgsType;
export const PlasmicBoutonVoirLesOffres__ArgProps = new Array<ArgPropType>();

export type PlasmicBoutonVoirLesOffres__OverridesType = {
  buttonBase?: Flex__<"div">;
  text?: Flex__<"div">;
  iconArrow?: Flex__<"div">;
  svg?: Flex__<"svg">;
};

export interface DefaultBoutonVoirLesOffresProps {
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicBoutonVoirLesOffres__RenderFunc(props: {
  variants: PlasmicBoutonVoirLesOffres__VariantsArgs;
  args: PlasmicBoutonVoirLesOffres__ArgsType;
  overrides: PlasmicBoutonVoirLesOffres__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  return (
    <div
      data-plasmic-name={"buttonBase"}
      data-plasmic-override={overrides.buttonBase}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        plasmic_library_tailwind_3_4_number_tokens_css.plasmic_tokens,
        plasmic_plasmic_rich_components_css.plasmic_tokens,
        sty.buttonBase
      )}
    >
      <div
        data-plasmic-name={"text"}
        data-plasmic-override={overrides.text}
        className={classNames(projectcss.all, projectcss.__wab_text, sty.text)}
      >
        {"Voir les offres d\u2019emplois"}
      </div>
      <div
        data-plasmic-name={"iconArrow"}
        data-plasmic-override={overrides.iconArrow}
        className={classNames(projectcss.all, sty.iconArrow)}
      >
        <GroupIcon
          data-plasmic-name={"svg"}
          data-plasmic-override={overrides.svg}
          className={classNames(projectcss.all, sty.svg)}
          role={"img"}
        />
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  buttonBase: ["buttonBase", "text", "iconArrow", "svg"],
  text: ["text"],
  iconArrow: ["iconArrow", "svg"],
  svg: ["svg"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  buttonBase: "div";
  text: "div";
  iconArrow: "div";
  svg: "svg";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicBoutonVoirLesOffres__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicBoutonVoirLesOffres__VariantsArgs;
    args?: PlasmicBoutonVoirLesOffres__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicBoutonVoirLesOffres__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicBoutonVoirLesOffres__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicBoutonVoirLesOffres__ArgProps,
          internalVariantPropNames: PlasmicBoutonVoirLesOffres__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicBoutonVoirLesOffres__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "buttonBase") {
    func.displayName = "PlasmicBoutonVoirLesOffres";
  } else {
    func.displayName = `PlasmicBoutonVoirLesOffres.${nodeName}`;
  }
  return func;
}

export const PlasmicBoutonVoirLesOffres = Object.assign(
  // Top-level PlasmicBoutonVoirLesOffres renders the root element
  makeNodeComponent("buttonBase"),
  {
    // Helper components rendering sub-elements
    text: makeNodeComponent("text"),
    iconArrow: makeNodeComponent("iconArrow"),
    svg: makeNodeComponent("svg"),

    // Metadata about props expected for PlasmicBoutonVoirLesOffres
    internalVariantProps: PlasmicBoutonVoirLesOffres__VariantProps,
    internalArgProps: PlasmicBoutonVoirLesOffres__ArgProps
  }
);

export default PlasmicBoutonVoirLesOffres;
/* prettier-ignore-end */
