/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: f7DE9y7qp46fyCw5nuY8f9
// Component: G-VPSgrlJgFQ

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { usePlasmicDataSourceContext } from "@plasmicapp/data-sources-context";
import {
  executePlasmicDataOp,
  usePlasmicDataOp,
  usePlasmicInvalidate
} from "@plasmicapp/react-web/lib/data-sources";

import { useScreenVariants as useScreenVariantshm8Nko4B5BDd } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: HM8Nko4B5BDd/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_library_tailwind_3_4_number_tokens_css from "../library_tailwind_3_4_number_tokens/plasmic.module.css"; // plasmic-import: 4vjRXvnb4XuY6J15w9oRcQ/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: f7DE9y7qp46fyCw5nuY8f9/projectcss
import sty from "./PlasmicRegisterGoogleValidation.module.css"; // plasmic-import: G-VPSgrlJgFQ/css

import PictogramIcon from "./icons/PlasmicIcon__Pictogram"; // plasmic-import: KlZQiGxQTluF/icon

createPlasmicElementProxy;

export type PlasmicRegisterGoogleValidation__VariantMembers = {};
export type PlasmicRegisterGoogleValidation__VariantsArgs = {};
type VariantPropType = keyof PlasmicRegisterGoogleValidation__VariantsArgs;
export const PlasmicRegisterGoogleValidation__VariantProps =
  new Array<VariantPropType>();

export type PlasmicRegisterGoogleValidation__ArgsType = {};
type ArgPropType = keyof PlasmicRegisterGoogleValidation__ArgsType;
export const PlasmicRegisterGoogleValidation__ArgProps =
  new Array<ArgPropType>();

export type PlasmicRegisterGoogleValidation__OverridesType = {
  root?: Flex__<"div">;
  user?: Flex__<"div">;
  imageWrapper?: Flex__<"div">;
  logoWrapper?: Flex__<"div">;
  svg?: Flex__<"svg">;
  baseline?: Flex__<"div">;
  frame?: Flex__<"div">;
  frame2?: Flex__<"div">;
  frame3?: Flex__<"div">;
  contentWrapper?: Flex__<"div">;
  title?: Flex__<"div">;
  heading?: Flex__<"div">;
  wrapper?: Flex__<"div">;
  tileButton?: Flex__<"button">;
  text?: Flex__<"div">;
  tileButton2?: Flex__<"button">;
  text2?: Flex__<"div">;
};

export interface DefaultRegisterGoogleValidationProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicRegisterGoogleValidation__RenderFunc(props: {
  variants: PlasmicRegisterGoogleValidation__VariantsArgs;
  args: PlasmicRegisterGoogleValidation__ArgsType;
  overrides: PlasmicRegisterGoogleValidation__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const dataSourcesCtx = usePlasmicDataSourceContext();
  const plasmicInvalidate = usePlasmicInvalidate();

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantshm8Nko4B5BDd()
  });

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            plasmic_library_tailwind_3_4_number_tokens_css.plasmic_tokens,
            plasmic_plasmic_rich_components_css.plasmic_tokens,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"user"}
            data-plasmic-override={overrides.user}
            className={classNames(projectcss.all, sty.user)}
          >
            <div
              data-plasmic-name={"imageWrapper"}
              data-plasmic-override={overrides.imageWrapper}
              className={classNames(projectcss.all, sty.imageWrapper)}
            >
              <div
                data-plasmic-name={"logoWrapper"}
                data-plasmic-override={overrides.logoWrapper}
                className={classNames(projectcss.all, sty.logoWrapper)}
                onClick={async event => {
                  const $steps = {};

                  $steps["goToAccueil"] = true
                    ? (() => {
                        const actionArgs = { destination: `/` };
                        return (({ destination }) => {
                          if (
                            typeof destination === "string" &&
                            destination.startsWith("#")
                          ) {
                            document
                              .getElementById(destination.substr(1))
                              .scrollIntoView({ behavior: "smooth" });
                          } else {
                            __nextRouter?.push(destination);
                          }
                        })?.apply(null, [actionArgs]);
                      })()
                    : undefined;
                  if (
                    $steps["goToAccueil"] != null &&
                    typeof $steps["goToAccueil"] === "object" &&
                    typeof $steps["goToAccueil"].then === "function"
                  ) {
                    $steps["goToAccueil"] = await $steps["goToAccueil"];
                  }
                }}
              >
                <PictogramIcon
                  data-plasmic-name={"svg"}
                  data-plasmic-override={overrides.svg}
                  className={classNames(projectcss.all, sty.svg)}
                  role={"img"}
                />

                <div
                  data-plasmic-name={"baseline"}
                  data-plasmic-override={overrides.baseline}
                  className={classNames(projectcss.all, sty.baseline)}
                >
                  <div
                    data-plasmic-name={"frame"}
                    data-plasmic-override={overrides.frame}
                    className={classNames(projectcss.all, sty.frame)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__rzsUk
                      )}
                    >
                      {"JOB"}
                    </div>
                  </div>
                  <div
                    data-plasmic-name={"frame2"}
                    data-plasmic-override={overrides.frame2}
                    className={classNames(projectcss.all, sty.frame2)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__opvHn
                      )}
                    >
                      {"AROUND"}
                    </div>
                  </div>
                  <div
                    data-plasmic-name={"frame3"}
                    data-plasmic-override={overrides.frame3}
                    className={classNames(projectcss.all, sty.frame3)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___0UCtb
                      )}
                    >
                      {"ME"}
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div
              data-plasmic-name={"contentWrapper"}
              data-plasmic-override={overrides.contentWrapper}
              className={classNames(projectcss.all, sty.contentWrapper)}
            >
              <div
                data-plasmic-name={"title"}
                data-plasmic-override={overrides.title}
                className={classNames(projectcss.all, sty.title)}
              >
                <div
                  data-plasmic-name={"heading"}
                  data-plasmic-override={overrides.heading}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.heading
                  )}
                >
                  {"Votre inscription est en cours"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__i5Tw0
                  )}
                >
                  {"Vous \u00eates"}
                </div>
              </div>
              <div
                data-plasmic-name={"wrapper"}
                data-plasmic-override={overrides.wrapper}
                className={classNames(projectcss.all, sty.wrapper)}
              >
                <button
                  data-plasmic-name={"tileButton"}
                  data-plasmic-override={overrides.tileButton}
                  className={classNames(
                    projectcss.all,
                    projectcss.button,
                    sty.tileButton
                  )}
                  disabled={false}
                  onClick={async event => {
                    const $steps = {};

                    $steps["updateRole"] = true
                      ? (() => {
                          const actionArgs = {
                            dataOp: {
                              sourceId: "5T6gSzGCrEfYgV9rAkCoaD",
                              opId: "6ad5598d-1776-462a-996a-6c5b86f73627",
                              userArgs: {
                                body: [
                                  {
                                    userId: $ctx.SupabaseUser.user?.id,
                                    role: "User"
                                  }
                                ]
                              },
                              cacheKey: null,
                              invalidatedKeys: ["plasmic_refresh_all"],
                              roleId: null
                            }
                          };
                          return (async ({ dataOp, continueOnError }) => {
                            try {
                              const response = await executePlasmicDataOp(
                                dataOp,
                                {
                                  userAuthToken: dataSourcesCtx?.userAuthToken,
                                  user: dataSourcesCtx?.user
                                }
                              );
                              await plasmicInvalidate(dataOp.invalidatedKeys);
                              return response;
                            } catch (e) {
                              if (!continueOnError) {
                                throw e;
                              }
                              return e;
                            }
                          })?.apply(null, [actionArgs]);
                        })()
                      : undefined;
                    if (
                      $steps["updateRole"] != null &&
                      typeof $steps["updateRole"] === "object" &&
                      typeof $steps["updateRole"].then === "function"
                    ) {
                      $steps["updateRole"] = await $steps["updateRole"];
                    }

                    $steps["welcomeMail"] = false
                      ? (() => {
                          const actionArgs = {
                            dataOp: {
                              sourceId: "5T6gSzGCrEfYgV9rAkCoaD",
                              opId: "794daa1a-97ba-4079-8f3e-f23db61377b4",
                              userArgs: {
                                body: [
                                  {
                                    to: `${$ctx.SupabaseUser.user?.email}`,
                                    template: "welcomeCandidat",
                                    subject: "Bienvenue {{name}} !",
                                    params: {
                                      name: `${$ctx.SupabaseUser.user?.firstName}`
                                    }
                                  }
                                ]
                              },
                              cacheKey: null,
                              invalidatedKeys: ["plasmic_refresh_all"],
                              roleId: null
                            }
                          };
                          return (async ({ dataOp, continueOnError }) => {
                            try {
                              const response = await executePlasmicDataOp(
                                dataOp,
                                {
                                  userAuthToken: dataSourcesCtx?.userAuthToken,
                                  user: dataSourcesCtx?.user
                                }
                              );
                              await plasmicInvalidate(dataOp.invalidatedKeys);
                              return response;
                            } catch (e) {
                              if (!continueOnError) {
                                throw e;
                              }
                              return e;
                            }
                          })?.apply(null, [actionArgs]);
                        })()
                      : undefined;
                    if (
                      $steps["welcomeMail"] != null &&
                      typeof $steps["welcomeMail"] === "object" &&
                      typeof $steps["welcomeMail"].then === "function"
                    ) {
                      $steps["welcomeMail"] = await $steps["welcomeMail"];
                    }

                    $steps["goToParametresCandidat"] = true
                      ? (() => {
                          const actionArgs = {
                            destination: `/parametres-candidat`
                          };
                          return (({ destination }) => {
                            if (
                              typeof destination === "string" &&
                              destination.startsWith("#")
                            ) {
                              document
                                .getElementById(destination.substr(1))
                                .scrollIntoView({ behavior: "smooth" });
                            } else {
                              __nextRouter?.push(destination);
                            }
                          })?.apply(null, [actionArgs]);
                        })()
                      : undefined;
                    if (
                      $steps["goToParametresCandidat"] != null &&
                      typeof $steps["goToParametresCandidat"] === "object" &&
                      typeof $steps["goToParametresCandidat"].then ===
                        "function"
                    ) {
                      $steps["goToParametresCandidat"] = await $steps[
                        "goToParametresCandidat"
                      ];
                    }
                  }}
                  ref={ref => {
                    $refs["tileButton"] = ref;
                  }}
                >
                  <div
                    data-plasmic-name={"text"}
                    data-plasmic-override={overrides.text}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text
                    )}
                  >
                    {"candidat"}
                  </div>
                </button>
                <button
                  data-plasmic-name={"tileButton2"}
                  data-plasmic-override={overrides.tileButton2}
                  className={classNames(
                    projectcss.all,
                    projectcss.button,
                    sty.tileButton2
                  )}
                  onClick={async event => {
                    const $steps = {};

                    $steps["updateRole"] = true
                      ? (() => {
                          const actionArgs = {
                            dataOp: {
                              sourceId: "5T6gSzGCrEfYgV9rAkCoaD",
                              opId: "6ad5598d-1776-462a-996a-6c5b86f73627",
                              userArgs: {
                                body: [
                                  {
                                    userId: $ctx.SupabaseUser.user?.id,
                                    role: "Company"
                                  }
                                ]
                              },
                              cacheKey: null,
                              invalidatedKeys: ["plasmic_refresh_all"],
                              roleId: null
                            }
                          };
                          return (async ({ dataOp, continueOnError }) => {
                            try {
                              const response = await executePlasmicDataOp(
                                dataOp,
                                {
                                  userAuthToken: dataSourcesCtx?.userAuthToken,
                                  user: dataSourcesCtx?.user
                                }
                              );
                              await plasmicInvalidate(dataOp.invalidatedKeys);
                              return response;
                            } catch (e) {
                              if (!continueOnError) {
                                throw e;
                              }
                              return e;
                            }
                          })?.apply(null, [actionArgs]);
                        })()
                      : undefined;
                    if (
                      $steps["updateRole"] != null &&
                      typeof $steps["updateRole"] === "object" &&
                      typeof $steps["updateRole"].then === "function"
                    ) {
                      $steps["updateRole"] = await $steps["updateRole"];
                    }

                    $steps["welcomeMail"] = false
                      ? (() => {
                          const actionArgs = {
                            dataOp: {
                              sourceId: "5T6gSzGCrEfYgV9rAkCoaD",
                              opId: "03e979d9-eab0-4428-b3c6-004fa4cebea6",
                              userArgs: {},
                              cacheKey: null,
                              invalidatedKeys: ["plasmic_refresh_all"],
                              roleId: null
                            }
                          };
                          return (async ({ dataOp, continueOnError }) => {
                            try {
                              const response = await executePlasmicDataOp(
                                dataOp,
                                {
                                  userAuthToken: dataSourcesCtx?.userAuthToken,
                                  user: dataSourcesCtx?.user
                                }
                              );
                              await plasmicInvalidate(dataOp.invalidatedKeys);
                              return response;
                            } catch (e) {
                              if (!continueOnError) {
                                throw e;
                              }
                              return e;
                            }
                          })?.apply(null, [actionArgs]);
                        })()
                      : undefined;
                    if (
                      $steps["welcomeMail"] != null &&
                      typeof $steps["welcomeMail"] === "object" &&
                      typeof $steps["welcomeMail"].then === "function"
                    ) {
                      $steps["welcomeMail"] = await $steps["welcomeMail"];
                    }

                    $steps["goToOffreEmployeur"] = true
                      ? (() => {
                          const actionArgs = {
                            destination: `/offre-employeur`
                          };
                          return (({ destination }) => {
                            if (
                              typeof destination === "string" &&
                              destination.startsWith("#")
                            ) {
                              document
                                .getElementById(destination.substr(1))
                                .scrollIntoView({ behavior: "smooth" });
                            } else {
                              __nextRouter?.push(destination);
                            }
                          })?.apply(null, [actionArgs]);
                        })()
                      : undefined;
                    if (
                      $steps["goToOffreEmployeur"] != null &&
                      typeof $steps["goToOffreEmployeur"] === "object" &&
                      typeof $steps["goToOffreEmployeur"].then === "function"
                    ) {
                      $steps["goToOffreEmployeur"] = await $steps[
                        "goToOffreEmployeur"
                      ];
                    }
                  }}
                  ref={ref => {
                    $refs["tileButton2"] = ref;
                  }}
                >
                  <div
                    data-plasmic-name={"text2"}
                    data-plasmic-override={overrides.text2}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text2
                    )}
                  >
                    {"employeur"}
                  </div>
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "user",
    "imageWrapper",
    "logoWrapper",
    "svg",
    "baseline",
    "frame",
    "frame2",
    "frame3",
    "contentWrapper",
    "title",
    "heading",
    "wrapper",
    "tileButton",
    "text",
    "tileButton2",
    "text2"
  ],
  user: [
    "user",
    "imageWrapper",
    "logoWrapper",
    "svg",
    "baseline",
    "frame",
    "frame2",
    "frame3",
    "contentWrapper",
    "title",
    "heading",
    "wrapper",
    "tileButton",
    "text",
    "tileButton2",
    "text2"
  ],
  imageWrapper: [
    "imageWrapper",
    "logoWrapper",
    "svg",
    "baseline",
    "frame",
    "frame2",
    "frame3"
  ],
  logoWrapper: ["logoWrapper", "svg", "baseline", "frame", "frame2", "frame3"],
  svg: ["svg"],
  baseline: ["baseline", "frame", "frame2", "frame3"],
  frame: ["frame"],
  frame2: ["frame2"],
  frame3: ["frame3"],
  contentWrapper: [
    "contentWrapper",
    "title",
    "heading",
    "wrapper",
    "tileButton",
    "text",
    "tileButton2",
    "text2"
  ],
  title: ["title", "heading"],
  heading: ["heading"],
  wrapper: ["wrapper", "tileButton", "text", "tileButton2", "text2"],
  tileButton: ["tileButton", "text"],
  text: ["text"],
  tileButton2: ["tileButton2", "text2"],
  text2: ["text2"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  user: "div";
  imageWrapper: "div";
  logoWrapper: "div";
  svg: "svg";
  baseline: "div";
  frame: "div";
  frame2: "div";
  frame3: "div";
  contentWrapper: "div";
  title: "div";
  heading: "div";
  wrapper: "div";
  tileButton: "button";
  text: "div";
  tileButton2: "button";
  text2: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicRegisterGoogleValidation__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicRegisterGoogleValidation__VariantsArgs;
    args?: PlasmicRegisterGoogleValidation__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicRegisterGoogleValidation__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicRegisterGoogleValidation__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicRegisterGoogleValidation__ArgProps,
          internalVariantPropNames:
            PlasmicRegisterGoogleValidation__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicRegisterGoogleValidation__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicRegisterGoogleValidation";
  } else {
    func.displayName = `PlasmicRegisterGoogleValidation.${nodeName}`;
  }
  return func;
}

export const PlasmicRegisterGoogleValidation = Object.assign(
  // Top-level PlasmicRegisterGoogleValidation renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    user: makeNodeComponent("user"),
    imageWrapper: makeNodeComponent("imageWrapper"),
    logoWrapper: makeNodeComponent("logoWrapper"),
    svg: makeNodeComponent("svg"),
    baseline: makeNodeComponent("baseline"),
    frame: makeNodeComponent("frame"),
    frame2: makeNodeComponent("frame2"),
    frame3: makeNodeComponent("frame3"),
    contentWrapper: makeNodeComponent("contentWrapper"),
    title: makeNodeComponent("title"),
    heading: makeNodeComponent("heading"),
    wrapper: makeNodeComponent("wrapper"),
    tileButton: makeNodeComponent("tileButton"),
    text: makeNodeComponent("text"),
    tileButton2: makeNodeComponent("tileButton2"),
    text2: makeNodeComponent("text2"),

    // Metadata about props expected for PlasmicRegisterGoogleValidation
    internalVariantProps: PlasmicRegisterGoogleValidation__VariantProps,
    internalArgProps: PlasmicRegisterGoogleValidation__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicRegisterGoogleValidation;
/* prettier-ignore-end */
