/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: f7DE9y7qp46fyCw5nuY8f9
// Component: M06HuWMcBQV2

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import SideBarButton from "../../SideBarButton"; // plasmic-import: QWOZXZk1eTc0/component

import { useScreenVariants as useScreenVariantshm8Nko4B5BDd } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: HM8Nko4B5BDd/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_library_tailwind_3_4_number_tokens_css from "../library_tailwind_3_4_number_tokens/plasmic.module.css"; // plasmic-import: 4vjRXvnb4XuY6J15w9oRcQ/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: f7DE9y7qp46fyCw5nuY8f9/projectcss
import sty from "./PlasmicSidebar.module.css"; // plasmic-import: M06HuWMcBQV2/css

import Pictogram2Icon from "./icons/PlasmicIcon__Pictogram2"; // plasmic-import: 6mBt3D9w7c35/icon
import SearchIcon from "./icons/PlasmicIcon__Search"; // plasmic-import: PEpkd9PswE7k/icon
import PictogramIcon from "./icons/PlasmicIcon__Pictogram"; // plasmic-import: KlZQiGxQTluF/icon
import GridFourIcon from "./icons/PlasmicIcon__GridFour"; // plasmic-import: KzAe7cfwmhYT/icon
import HeartStraightIcon from "./icons/PlasmicIcon__HeartStraight"; // plasmic-import: 2A8amxR7FAse/icon
import PhGearFillIcon from "./icons/PlasmicIcon__PhGearFill"; // plasmic-import: M0oN64eO6n3z/icon
import EnvelopeSimple2Icon from "./icons/PlasmicIcon__EnvelopeSimple2"; // plasmic-import: 44ROc7g2Vqof/icon
import SolarLogoutOutlineIcon from "./icons/PlasmicIcon__SolarLogoutOutline"; // plasmic-import: UZfkN-2mqbQ1/icon

createPlasmicElementProxy;

export type PlasmicSidebar__VariantMembers = {};
export type PlasmicSidebar__VariantsArgs = {};
type VariantPropType = keyof PlasmicSidebar__VariantsArgs;
export const PlasmicSidebar__VariantProps = new Array<VariantPropType>();

export type PlasmicSidebar__ArgsType = {};
type ArgPropType = keyof PlasmicSidebar__ArgsType;
export const PlasmicSidebar__ArgProps = new Array<ArgPropType>();

export type PlasmicSidebar__OverridesType = {
  sidebarMenu?: Flex__<"nav">;
  logoWrapper?: Flex__<"a"> & Partial<LinkProps>;
  container?: Flex__<"div">;
  links?: Flex__<"div">;
  disconnectButton?: Flex__<"div">;
  link?: Flex__<"a"> & Partial<LinkProps>;
};

export interface DefaultSidebarProps {
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicSidebar__RenderFunc(props: {
  variants: PlasmicSidebar__VariantsArgs;
  args: PlasmicSidebar__ArgsType;
  overrides: PlasmicSidebar__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const $globalActions = useGlobalActions?.();

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantshm8Nko4B5BDd()
  });

  return (
    <Stack__
      as={"nav"}
      data-plasmic-name={"sidebarMenu"}
      data-plasmic-override={overrides.sidebarMenu}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        plasmic_library_tailwind_3_4_number_tokens_css.plasmic_tokens,
        plasmic_plasmic_rich_components_css.plasmic_tokens,
        sty.sidebarMenu
      )}
    >
      <Stack__
        as={PlasmicLink__}
        data-plasmic-name={"logoWrapper"}
        data-plasmic-override={overrides.logoWrapper}
        hasGap={true}
        className={classNames(projectcss.all, projectcss.a, sty.logoWrapper)}
        component={Link}
        onClick={async event => {
          const $steps = {};

          $steps["goToAccueil"] = true
            ? (() => {
                const actionArgs = { destination: `/` };
                return (({ destination }) => {
                  if (
                    typeof destination === "string" &&
                    destination.startsWith("#")
                  ) {
                    document
                      .getElementById(destination.substr(1))
                      .scrollIntoView({ behavior: "smooth" });
                  } else {
                    __nextRouter?.push(destination);
                  }
                })?.apply(null, [actionArgs]);
              })()
            : undefined;
          if (
            $steps["goToAccueil"] != null &&
            typeof $steps["goToAccueil"] === "object" &&
            typeof $steps["goToAccueil"].then === "function"
          ) {
            $steps["goToAccueil"] = await $steps["goToAccueil"];
          }
        }}
        platform={"nextjs"}
      >
        <Pictogram2Icon
          className={classNames(projectcss.all, sty.svg__uPc3B)}
          role={"img"}
        />

        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__vpz1D
          )}
        >
          {"JOB AROUND ME"}
        </div>
      </Stack__>
      <div
        data-plasmic-name={"container"}
        data-plasmic-override={overrides.container}
        className={classNames(projectcss.all, sty.container)}
      >
        <Stack__
          as={"div"}
          data-plasmic-name={"links"}
          data-plasmic-override={overrides.links}
          hasGap={true}
          className={classNames(projectcss.all, sty.links)}
        >
          <SideBarButton
            className={classNames("__wab_instance", sty.sideBarButton__ybHin)}
            iconStart={true}
            label={
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__pYn1Z
                )}
              >
                {"Recherche job"}
              </div>
            }
            onClick={async event => {
              const $steps = {};

              $steps["goToAccueil"] = true
                ? (() => {
                    const actionArgs = { destination: `/` };
                    return (({ destination }) => {
                      if (
                        typeof destination === "string" &&
                        destination.startsWith("#")
                      ) {
                        document
                          .getElementById(destination.substr(1))
                          .scrollIntoView({ behavior: "smooth" });
                      } else {
                        __nextRouter?.push(destination);
                      }
                    })?.apply(null, [actionArgs]);
                  })()
                : undefined;
              if (
                $steps["goToAccueil"] != null &&
                typeof $steps["goToAccueil"] === "object" &&
                typeof $steps["goToAccueil"].then === "function"
              ) {
                $steps["goToAccueil"] = await $steps["goToAccueil"];
              }
            }}
            start={
              <SearchIcon
                className={classNames(projectcss.all, sty.svg__szCwB)}
                role={"img"}
              />
            }
            type={(() => {
              try {
                return $ctx.pagePath === "/" ? "actif" : "";
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return "actif";
                }
                throw e;
              }
            })()}
          />

          <SideBarButton
            className={classNames("__wab_instance", sty.sideBarButton__eQp4)}
            iconStart={true}
            label={
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__mXn1A
                )}
              >
                {"Mes candidatures"}
              </div>
            }
            onClick={async event => {
              const $steps = {};

              $steps["goToMesCandidatures"] = true
                ? (() => {
                    const actionArgs = { destination: `/candidatures` };
                    return (({ destination }) => {
                      if (
                        typeof destination === "string" &&
                        destination.startsWith("#")
                      ) {
                        document
                          .getElementById(destination.substr(1))
                          .scrollIntoView({ behavior: "smooth" });
                      } else {
                        __nextRouter?.push(destination);
                      }
                    })?.apply(null, [actionArgs]);
                  })()
                : undefined;
              if (
                $steps["goToMesCandidatures"] != null &&
                typeof $steps["goToMesCandidatures"] === "object" &&
                typeof $steps["goToMesCandidatures"].then === "function"
              ) {
                $steps["goToMesCandidatures"] = await $steps[
                  "goToMesCandidatures"
                ];
              }
            }}
            start={
              <GridFourIcon
                className={classNames(projectcss.all, sty.svg__onoj8)}
                role={"img"}
              />
            }
            type={(() => {
              try {
                return $ctx.pagePath === "/candidatures" ? "actif" : "";
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return "actif";
                }
                throw e;
              }
            })()}
          />

          <SideBarButton
            className={classNames("__wab_instance", sty.sideBarButton__unDnB)}
            iconStart={true}
            label={
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__yj6GY
                )}
              >
                {"Mes annonces"}
              </div>
            }
            onClick={async event => {
              const $steps = {};

              $steps["goToMesAnnonces"] = true
                ? (() => {
                    const actionArgs = { destination: `/annonces` };
                    return (({ destination }) => {
                      if (
                        typeof destination === "string" &&
                        destination.startsWith("#")
                      ) {
                        document
                          .getElementById(destination.substr(1))
                          .scrollIntoView({ behavior: "smooth" });
                      } else {
                        __nextRouter?.push(destination);
                      }
                    })?.apply(null, [actionArgs]);
                  })()
                : undefined;
              if (
                $steps["goToMesAnnonces"] != null &&
                typeof $steps["goToMesAnnonces"] === "object" &&
                typeof $steps["goToMesAnnonces"].then === "function"
              ) {
                $steps["goToMesAnnonces"] = await $steps["goToMesAnnonces"];
              }
            }}
            start={
              <HeartStraightIcon
                className={classNames(projectcss.all, sty.svg__xNuo3)}
                role={"img"}
              />
            }
            type={(() => {
              try {
                return $ctx.pagePath === "/annonces" ? "actif" : "";
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return "actif";
                }
                throw e;
              }
            })()}
          />

          <SideBarButton
            className={classNames("__wab_instance", sty.sideBarButton__uGb2)}
            iconStart={true}
            label={
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__nghUf
                )}
              >
                {"parametres"}
              </div>
            }
            onClick={async event => {
              const $steps = {};

              $steps["goToParametresDeCompte"] = true
                ? (() => {
                    const actionArgs = { destination: `/parametres` };
                    return (({ destination }) => {
                      if (
                        typeof destination === "string" &&
                        destination.startsWith("#")
                      ) {
                        document
                          .getElementById(destination.substr(1))
                          .scrollIntoView({ behavior: "smooth" });
                      } else {
                        __nextRouter?.push(destination);
                      }
                    })?.apply(null, [actionArgs]);
                  })()
                : undefined;
              if (
                $steps["goToParametresDeCompte"] != null &&
                typeof $steps["goToParametresDeCompte"] === "object" &&
                typeof $steps["goToParametresDeCompte"].then === "function"
              ) {
                $steps["goToParametresDeCompte"] = await $steps[
                  "goToParametresDeCompte"
                ];
              }
            }}
            start={
              <PhGearFillIcon
                className={classNames(projectcss.all, sty.svg___7PPcX)}
                role={"img"}
              />
            }
            type={(() => {
              try {
                return $ctx.pagePath === "/parametres" ? "actif" : "";
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return "actif";
                }
                throw e;
              }
            })()}
          />

          <SideBarButton
            className={classNames("__wab_instance", sty.sideBarButton__xlKVn)}
            iconStart={true}
            label={
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__lb6Xu
                )}
              >
                {"mes alertes"}
              </div>
            }
            onClick={async event => {
              const $steps = {};

              $steps["goToMesAlertes"] = true
                ? (() => {
                    const actionArgs = { destination: `/alertes` };
                    return (({ destination }) => {
                      if (
                        typeof destination === "string" &&
                        destination.startsWith("#")
                      ) {
                        document
                          .getElementById(destination.substr(1))
                          .scrollIntoView({ behavior: "smooth" });
                      } else {
                        __nextRouter?.push(destination);
                      }
                    })?.apply(null, [actionArgs]);
                  })()
                : undefined;
              if (
                $steps["goToMesAlertes"] != null &&
                typeof $steps["goToMesAlertes"] === "object" &&
                typeof $steps["goToMesAlertes"].then === "function"
              ) {
                $steps["goToMesAlertes"] = await $steps["goToMesAlertes"];
              }
            }}
            start={
              <EnvelopeSimple2Icon
                className={classNames(projectcss.all, sty.svg__x4G2D)}
                role={"img"}
              />
            }
            type={(() => {
              try {
                return $ctx.pagePath === "/alertes" ? "actif" : "";
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return "actif";
                }
                throw e;
              }
            })()}
          />
        </Stack__>
        <Stack__
          as={"div"}
          data-plasmic-name={"disconnectButton"}
          data-plasmic-override={overrides.disconnectButton}
          hasGap={true}
          className={classNames(projectcss.all, sty.disconnectButton)}
        >
          <SolarLogoutOutlineIcon
            className={classNames(projectcss.all, sty.svg__qm6FN)}
            role={"img"}
          />

          <PlasmicLink__
            data-plasmic-name={"link"}
            data-plasmic-override={overrides.link}
            className={classNames(
              projectcss.all,
              projectcss.a,
              projectcss.__wab_text,
              sty.link
            )}
            component={Link}
            href={""}
            onClick={async event => {
              const $steps = {};

              $steps["invokeGlobalAction"] = true
                ? (() => {
                    const actionArgs = { args: ["/login"] };
                    return $globalActions[
                      "SupabaseUserGlobalContext.logout"
                    ]?.apply(null, [...actionArgs.args]);
                  })()
                : undefined;
              if (
                $steps["invokeGlobalAction"] != null &&
                typeof $steps["invokeGlobalAction"] === "object" &&
                typeof $steps["invokeGlobalAction"].then === "function"
              ) {
                $steps["invokeGlobalAction"] = await $steps[
                  "invokeGlobalAction"
                ];
              }
            }}
            platform={"nextjs"}
          >
            {"D\u00e9connexion"}
          </PlasmicLink__>
          <SideBarButton
            className={classNames("__wab_instance", sty.sideBarButton__bG6GX)}
            iconStart={true}
            label={
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__jJnT7
                )}
              >
                {"D\u00e9connexion"}
              </div>
            }
            onClick={async event => {
              const $steps = {};

              $steps["invokeGlobalAction"] = true
                ? (() => {
                    const actionArgs = { args: ["/"] };
                    return $globalActions[
                      "SupabaseUserGlobalContext.logout"
                    ]?.apply(null, [...actionArgs.args]);
                  })()
                : undefined;
              if (
                $steps["invokeGlobalAction"] != null &&
                typeof $steps["invokeGlobalAction"] === "object" &&
                typeof $steps["invokeGlobalAction"].then === "function"
              ) {
                $steps["invokeGlobalAction"] = await $steps[
                  "invokeGlobalAction"
                ];
              }
            }}
            start={
              <SolarLogoutOutlineIcon
                className={classNames(projectcss.all, sty.svg__jHbiR)}
                role={"img"}
              />
            }
            type={(() => {
              try {
                return $ctx.pagePath === "/" ? "actif" : "";
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return "actif";
                }
                throw e;
              }
            })()}
          />
        </Stack__>
      </div>
    </Stack__>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  sidebarMenu: [
    "sidebarMenu",
    "logoWrapper",
    "container",
    "links",
    "disconnectButton",
    "link"
  ],
  logoWrapper: ["logoWrapper"],
  container: ["container", "links", "disconnectButton", "link"],
  links: ["links"],
  disconnectButton: ["disconnectButton", "link"],
  link: ["link"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  sidebarMenu: "nav";
  logoWrapper: "a";
  container: "div";
  links: "div";
  disconnectButton: "div";
  link: "a";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicSidebar__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicSidebar__VariantsArgs;
    args?: PlasmicSidebar__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicSidebar__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicSidebar__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicSidebar__ArgProps,
          internalVariantPropNames: PlasmicSidebar__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicSidebar__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "sidebarMenu") {
    func.displayName = "PlasmicSidebar";
  } else {
    func.displayName = `PlasmicSidebar.${nodeName}`;
  }
  return func;
}

export const PlasmicSidebar = Object.assign(
  // Top-level PlasmicSidebar renders the root element
  makeNodeComponent("sidebarMenu"),
  {
    // Helper components rendering sub-elements
    logoWrapper: makeNodeComponent("logoWrapper"),
    container: makeNodeComponent("container"),
    links: makeNodeComponent("links"),
    disconnectButton: makeNodeComponent("disconnectButton"),
    link: makeNodeComponent("link"),

    // Metadata about props expected for PlasmicSidebar
    internalVariantProps: PlasmicSidebar__VariantProps,
    internalArgProps: PlasmicSidebar__ArgProps
  }
);

export default PlasmicSidebar;
/* prettier-ignore-end */
