/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: f7DE9y7qp46fyCw5nuY8f9
// Component: urNyxs5aX-pA

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { usePlasmicDataSourceContext } from "@plasmicapp/data-sources-context";
import {
  executePlasmicDataOp,
  usePlasmicDataOp,
  usePlasmicInvalidate
} from "@plasmicapp/react-web/lib/data-sources";

import Slidebar from "../../Slidebar"; // plasmic-import: M06HuWMcBQV2/component
import { FormWrapper } from "@plasmicpkgs/antd5/skinny/Form";
import { formHelpers as FormWrapper_Helpers } from "@plasmicpkgs/antd5/skinny/Form";
import { FormItemWrapper } from "@plasmicpkgs/antd5/skinny/FormItem";
import TextInput from "../../TextInput"; // plasmic-import: pZ7Ql6sUFRw9/component
import { PhoneSelector } from "../../forms/PhoneSelector/PhoneSelector"; // plasmic-import: sOyePdANTQ6t/codeComponent
import Select from "../../Select"; // plasmic-import: ZMB-SB-xJDyQ/component
import MenuItem from "../../MenuItem"; // plasmic-import: plmAgyhhAdMc/component
import MenuSection from "../../MenuSection"; // plasmic-import: MUvYPH7rZO6i/component
import { AntdTextArea } from "@plasmicpkgs/antd5/skinny/registerInput";
import { inputHelpers as AntdTextArea_Helpers } from "@plasmicpkgs/antd5/skinny/registerInput";
import { AntdButton } from "@plasmicpkgs/antd5/skinny/registerButton";
import { FileUploader } from "../../others/FileUploader/FileUploader"; // plasmic-import: RpVDoPZzyXH3/codeComponent
import { JamButton } from "../../forms/JamButton/JamButton"; // plasmic-import: UiI0wt2mxfuf/codeComponent
import { TextInput as TextInput2 } from "../../forms/TextInput/TextInput"; // plasmic-import: vyWUomJMQins/codeComponent
import { Fetcher } from "@plasmicapp/react-web/lib/data-sources";

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_library_tailwind_3_4_number_tokens_css from "../library_tailwind_3_4_number_tokens/plasmic.module.css"; // plasmic-import: 4vjRXvnb4XuY6J15w9oRcQ/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: f7DE9y7qp46fyCw5nuY8f9/projectcss
import sty from "./PlasmicParametresDeCompte.module.css"; // plasmic-import: urNyxs5aX-pA/css

import PhPencilSimpleIcon from "./icons/PlasmicIcon__PhPencilSimple"; // plasmic-import: 7xHLZEkolpKE/icon
import PhTrashIcon from "./icons/PlasmicIcon__PhTrash"; // plasmic-import: juO39VElEpcx/icon
import ToggleRightIcon from "./icons/PlasmicIcon__ToggleRight"; // plasmic-import: C0vfLu9wrlOh/icon

createPlasmicElementProxy;

export type PlasmicParametresDeCompte__VariantMembers = {};
export type PlasmicParametresDeCompte__VariantsArgs = {};
type VariantPropType = keyof PlasmicParametresDeCompte__VariantsArgs;
export const PlasmicParametresDeCompte__VariantProps =
  new Array<VariantPropType>();

export type PlasmicParametresDeCompte__ArgsType = {};
type ArgPropType = keyof PlasmicParametresDeCompte__ArgsType;
export const PlasmicParametresDeCompte__ArgProps = new Array<ArgPropType>();

export type PlasmicParametresDeCompte__OverridesType = {
  parametresDeCompte?: Flex__<"div">;
  slidebar?: Flex__<typeof Slidebar>;
  main?: Flex__<"main">;
  title?: Flex__<"div">;
  heading?: Flex__<"div">;
  container?: Flex__<"div">;
  informationsPersonnelles?: Flex__<"div">;
  frame1437254343?: Flex__<"div">;
  frame5?: Flex__<"div">;
  frame6?: Flex__<"div">;
  img?: Flex__<typeof PlasmicImg__>;
  editIcon?: Flex__<"div">;
  frame7?: Flex__<"div">;
  deleteIcon?: Flex__<"div">;
  frame8?: Flex__<"div">;
  tableCell?: Flex__<"div">;
  text6?: Flex__<"div">;
  textInputBase6?: Flex__<"div">;
  hintText6?: Flex__<"div">;
  formulaire?: Flex__<typeof FormWrapper>;
  prenomNom?: Flex__<"div">;
  firstName?: Flex__<typeof TextInput>;
  lastName?: Flex__<typeof TextInput>;
  textInput3?: Flex__<typeof TextInput>;
  telephone?: Flex__<"div">;
  phoneSelector?: Flex__<typeof PhoneSelector>;
  phoneNumber2?: Flex__<typeof TextInput>;
  rue?: Flex__<typeof TextInput>;
  codePostalVille?: Flex__<"div">;
  codePostal?: Flex__<typeof TextInput>;
  select?: Flex__<typeof Select>;
  pays?: Flex__<typeof TextInput>;
  textArea?: Flex__<typeof AntdTextArea>;
  niveauExperience?: Flex__<typeof Select>;
  textInput4?: Flex__<typeof TextInput>;
  button?: Flex__<typeof AntdButton>;
  cvModificationDuMdp?: Flex__<"div">;
  frame1437254287?: Flex__<"div">;
  card2?: Flex__<"div">;
  frame9?: Flex__<"div">;
  frame10?: Flex__<"div">;
  email?: Flex__<"div">;
  fileUploader?: Flex__<"div">;
  frame11?: Flex__<"div">;
  email2?: Flex__<"div">;
  fileUploader2?: Flex__<"div">;
  frame1437254288?: Flex__<"div">;
  freeBox?: Flex__<"div">;
  card3?: Flex__<"div">;
  form3?: Flex__<typeof FormWrapper>;
  inputWrapper8?: Flex__<"div">;
  wrapper?: Flex__<"div">;
  textInput9?: Flex__<typeof TextInput2>;
  wrapper2?: Flex__<"div">;
  progressBar?: Flex__<"div">;
  signedByBaseProgressBarSteppedMediumLabelNone?: Flex__<"div">;
  progress?: Flex__<"div">;
  inProgress?: Flex__<"div">;
  base?: Flex__<"div">;
  base2?: Flex__<"div">;
  base3?: Flex__<"div">;
  base4?: Flex__<"div">;
  base5?: Flex__<"div">;
  base6?: Flex__<"div">;
  text?: Flex__<"div">;
  inputWrapper9?: Flex__<"div">;
  wrapper3?: Flex__<"div">;
  textInput10?: Flex__<typeof TextInput2>;
};

export interface DefaultParametresDeCompteProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicParametresDeCompte__RenderFunc(props: {
  variants: PlasmicParametresDeCompte__VariantsArgs;
  args: PlasmicParametresDeCompte__ArgsType;
  overrides: PlasmicParametresDeCompte__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const $globalActions = useGlobalActions?.();

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "form3.value",
        type: "private",
        variableType: "object",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        refName: "form3",
        onMutate: generateOnMutateForSpec("value", FormWrapper_Helpers)
      },
      {
        path: "form3.isSubmitting",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => false,

        refName: "form3",
        onMutate: generateOnMutateForSpec("isSubmitting", FormWrapper_Helpers)
      },
      {
        path: "mdp1",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => ""
      },
      {
        path: "mdp2",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => ""
      },
      {
        path: "formulaire.value",
        type: "private",
        variableType: "object",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        refName: "formulaire",
        onMutate: generateOnMutateForSpec("value", FormWrapper_Helpers)
      },
      {
        path: "formulaire.isSubmitting",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => false,

        refName: "formulaire",
        onMutate: generateOnMutateForSpec("isSubmitting", FormWrapper_Helpers)
      },
      {
        path: "firstName.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined
      },
      {
        path: "lastName.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined
      },
      {
        path: "textInput3.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined
      },
      {
        path: "rue.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined
      },
      {
        path: "codePostal.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined
      },
      {
        path: "select.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined
      },
      {
        path: "pays.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined
      },
      {
        path: "textArea.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        onMutate: generateOnMutateForSpec("value", AntdTextArea_Helpers)
      },
      {
        path: "niveauExperience.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined
      },
      {
        path: "textInput4.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined
      },
      {
        path: "phoneNumber2.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });
  const dataSourcesCtx = usePlasmicDataSourceContext();
  const plasmicInvalidate = usePlasmicInvalidate();

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"parametresDeCompte"}
          data-plasmic-override={overrides.parametresDeCompte}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            plasmic_library_tailwind_3_4_number_tokens_css.plasmic_tokens,
            sty.parametresDeCompte
          )}
        >
          <Slidebar
            data-plasmic-name={"slidebar"}
            data-plasmic-override={overrides.slidebar}
            className={classNames("__wab_instance", sty.slidebar)}
          />

          <Stack__
            as={"main"}
            data-plasmic-name={"main"}
            data-plasmic-override={overrides.main}
            hasGap={true}
            className={classNames(projectcss.all, sty.main)}
          >
            <Stack__
              as={"div"}
              data-plasmic-name={"title"}
              data-plasmic-override={overrides.title}
              hasGap={true}
              className={classNames(projectcss.all, sty.title)}
            >
              <div
                data-plasmic-name={"heading"}
                data-plasmic-override={overrides.heading}
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.heading
                )}
              >
                {"Param\u00e8tres de compte"}
              </div>
            </Stack__>
            <Stack__
              as={"div"}
              data-plasmic-name={"container"}
              data-plasmic-override={overrides.container}
              hasGap={true}
              className={classNames(projectcss.all, sty.container)}
            >
              <div
                data-plasmic-name={"informationsPersonnelles"}
                data-plasmic-override={overrides.informationsPersonnelles}
                className={classNames(
                  projectcss.all,
                  sty.informationsPersonnelles
                )}
              >
                <Stack__
                  as={"div"}
                  data-plasmic-name={"frame1437254343"}
                  data-plasmic-override={overrides.frame1437254343}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.frame1437254343)}
                >
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"frame5"}
                    data-plasmic-override={overrides.frame5}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.frame5)}
                  >
                    <div
                      data-plasmic-name={"frame6"}
                      data-plasmic-override={overrides.frame6}
                      className={classNames(projectcss.all, sty.frame6)}
                    >
                      <PlasmicImg__
                        data-plasmic-name={"img"}
                        data-plasmic-override={overrides.img}
                        alt={""}
                        className={classNames(sty.img)}
                        displayHeight={"132px"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"132px"}
                        loading={"lazy"}
                        src={{
                          src: "/plasmic/jam_production_🚀/images/frame9.svg",
                          fullWidth: 132,
                          fullHeight: 132,
                          aspectRatio: 1
                        }}
                      />
                    </div>
                    <div
                      data-plasmic-name={"editIcon"}
                      data-plasmic-override={overrides.editIcon}
                      className={classNames(projectcss.all, sty.editIcon)}
                    >
                      <div
                        data-plasmic-name={"frame7"}
                        data-plasmic-override={overrides.frame7}
                        className={classNames(projectcss.all, sty.frame7)}
                      />

                      <PhPencilSimpleIcon
                        className={classNames(projectcss.all, sty.svg___5XUxq)}
                        role={"img"}
                      />
                    </div>
                    <div
                      data-plasmic-name={"deleteIcon"}
                      data-plasmic-override={overrides.deleteIcon}
                      className={classNames(projectcss.all, sty.deleteIcon)}
                    >
                      <div
                        data-plasmic-name={"frame8"}
                        data-plasmic-override={overrides.frame8}
                        className={classNames(projectcss.all, sty.frame8)}
                      />

                      <PhTrashIcon
                        className={classNames(projectcss.all, sty.svg__rF5F)}
                        role={"img"}
                      />
                    </div>
                  </Stack__>
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"tableCell"}
                    data-plasmic-override={overrides.tableCell}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.tableCell)}
                  >
                    <ToggleRightIcon
                      className={classNames(projectcss.all, sty.svg__zvZto)}
                      role={"img"}
                    />

                    <div
                      data-plasmic-name={"text6"}
                      data-plasmic-override={overrides.text6}
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text6
                      )}
                    >
                      {"En recherche active"}
                    </div>
                  </Stack__>
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"textInputBase6"}
                    data-plasmic-override={overrides.textInputBase6}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.textInputBase6)}
                  >
                    <div
                      data-plasmic-name={"hintText6"}
                      data-plasmic-override={overrides.hintText6}
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.hintText6
                      )}
                    >
                      {
                        'Votre statut "En recherche active" sera d\u00e9sactiv\u00e9 apr\u00e8s 48h. R\u00e9activez-le si vous \u00eates toujours en recherche active.'
                      }
                    </div>
                  </Stack__>
                </Stack__>
                {(() => {
                  const child$Props = {
                    className: classNames("__wab_instance", sty.formulaire),
                    extendedOnValuesChange: async (...eventArgs: any) => {
                      generateStateOnChangePropForCodeComponents(
                        $state,
                        "value",
                        ["formulaire", "value"],
                        FormWrapper_Helpers
                      ).apply(null, eventArgs);
                    },
                    formItems: [
                      { label: "Name", name: "name", inputType: "Text" },
                      {
                        label: "Message",
                        name: "message",
                        inputType: "Text Area"
                      }
                    ],
                    labelCol: { span: 8, horizontalOnly: true },
                    layout: "vertical",
                    mode: "advanced",
                    onFinish: async values => {
                      const $steps = {};

                      $steps["postgresUpdateById"] = true
                        ? (() => {
                            const actionArgs = {
                              dataOp: {
                                sourceId: "kVSSe8ab4TtzwRPnTeEeUp",
                                opId: "25b09f8c-a45e-4454-b4c9-7fa468f255b3",
                                userArgs: {
                                  variables: [$state.formulaire.value.email]
                                },
                                cacheKey: null,
                                invalidatedKeys: ["plasmic_refresh_all"],
                                roleId: null
                              }
                            };
                            return (async ({ dataOp, continueOnError }) => {
                              try {
                                const response = await executePlasmicDataOp(
                                  dataOp,
                                  {
                                    userAuthToken:
                                      dataSourcesCtx?.userAuthToken,
                                    user: dataSourcesCtx?.user
                                  }
                                );
                                await plasmicInvalidate(dataOp.invalidatedKeys);
                                return response;
                              } catch (e) {
                                if (!continueOnError) {
                                  throw e;
                                }
                                return e;
                              }
                            })?.apply(null, [actionArgs]);
                          })()
                        : undefined;
                      if (
                        $steps["postgresUpdateById"] != null &&
                        typeof $steps["postgresUpdateById"] === "object" &&
                        typeof $steps["postgresUpdateById"].then === "function"
                      ) {
                        $steps["postgresUpdateById"] = await $steps[
                          "postgresUpdateById"
                        ];
                      }
                    },
                    onIsSubmittingChange: async (...eventArgs: any) => {
                      generateStateOnChangePropForCodeComponents(
                        $state,
                        "isSubmitting",
                        ["formulaire", "isSubmitting"],
                        FormWrapper_Helpers
                      ).apply(null, eventArgs);
                    },
                    ref: ref => {
                      $refs["formulaire"] = ref;
                    },
                    submitSlot: null,
                    wrapperCol: { span: 16, horizontalOnly: true }
                  };
                  initializeCodeComponentStates(
                    $state,
                    [
                      {
                        name: "value",
                        plasmicStateName: "formulaire.value"
                      },
                      {
                        name: "isSubmitting",
                        plasmicStateName: "formulaire.isSubmitting"
                      }
                    ],
                    [],
                    FormWrapper_Helpers ?? {},
                    child$Props
                  );

                  return (
                    <FormWrapper
                      data-plasmic-name={"formulaire"}
                      data-plasmic-override={overrides.formulaire}
                      {...child$Props}
                    >
                      <Stack__
                        as={"div"}
                        data-plasmic-name={"prenomNom"}
                        data-plasmic-override={overrides.prenomNom}
                        hasGap={true}
                        className={classNames(projectcss.all, sty.prenomNom)}
                      >
                        <FormItemWrapper
                          className={classNames(
                            "__wab_instance",
                            sty.formField__gu1TP
                          )}
                          initialValue={""}
                          label={"Pr\u00e9nom*"}
                          name={"firstName"}
                        >
                          <TextInput
                            data-plasmic-name={"firstName"}
                            data-plasmic-override={overrides.firstName}
                            className={classNames(
                              "__wab_instance",
                              sty.firstName
                            )}
                            defaultValue={``}
                            onChange={async (...eventArgs: any) => {
                              generateStateOnChangeProp($state, [
                                "firstName",
                                "value"
                              ]).apply(null, eventArgs);

                              if (
                                eventArgs.length > 1 &&
                                eventArgs[1] &&
                                eventArgs[1]._plasmic_state_init_
                              ) {
                                return;
                              }
                            }}
                            placeholder={"Pr\u00e9nom"}
                          />
                        </FormItemWrapper>
                        <FormItemWrapper
                          className={classNames(
                            "__wab_instance",
                            sty.formField___4ZPYl
                          )}
                          initialValue={""}
                          label={"Nom*"}
                          name={"lastName"}
                        >
                          <TextInput
                            data-plasmic-name={"lastName"}
                            data-plasmic-override={overrides.lastName}
                            className={classNames(
                              "__wab_instance",
                              sty.lastName
                            )}
                            onChange={async (...eventArgs: any) => {
                              generateStateOnChangeProp($state, [
                                "lastName",
                                "value"
                              ]).apply(null, eventArgs);

                              if (
                                eventArgs.length > 1 &&
                                eventArgs[1] &&
                                eventArgs[1]._plasmic_state_init_
                              ) {
                                return;
                              }
                            }}
                            placeholder={"Nom"}
                          />
                        </FormItemWrapper>
                      </Stack__>
                      <FormItemWrapper
                        className={classNames(
                          "__wab_instance",
                          sty.formField__y2STw
                        )}
                        label={"Email*"}
                        name={"email"}
                      >
                        <TextInput
                          data-plasmic-name={"textInput3"}
                          data-plasmic-override={overrides.textInput3}
                          className={classNames(
                            "__wab_instance",
                            sty.textInput3
                          )}
                          onChange={async (...eventArgs: any) => {
                            generateStateOnChangeProp($state, [
                              "textInput3",
                              "value"
                            ]).apply(null, eventArgs);

                            if (
                              eventArgs.length > 1 &&
                              eventArgs[1] &&
                              eventArgs[1]._plasmic_state_init_
                            ) {
                              return;
                            }
                          }}
                          placeholder={"Email"}
                        />
                      </FormItemWrapper>
                      <Stack__
                        as={"div"}
                        data-plasmic-name={"telephone"}
                        data-plasmic-override={overrides.telephone}
                        hasGap={true}
                        className={classNames(projectcss.all, sty.telephone)}
                      >
                        <FormItemWrapper
                          className={classNames(
                            "__wab_instance",
                            sty.formField___8YUuA
                          )}
                          label={"T\u00e9l\u00e9phone"}
                          name={"countryCode"}
                        >
                          <PhoneSelector
                            data-plasmic-name={"phoneSelector"}
                            data-plasmic-override={overrides.phoneSelector}
                            className={classNames(
                              "__wab_instance",
                              sty.phoneSelector
                            )}
                          />
                        </FormItemWrapper>
                        <FormItemWrapper
                          className={classNames(
                            "__wab_instance",
                            sty.formField__qgKq5
                          )}
                          label={""}
                          name={"phoneNumber"}
                        >
                          <TextInput
                            data-plasmic-name={"phoneNumber2"}
                            data-plasmic-override={overrides.phoneNumber2}
                            className={classNames(
                              "__wab_instance",
                              sty.phoneNumber2
                            )}
                            onChange={async (...eventArgs: any) => {
                              generateStateOnChangeProp($state, [
                                "phoneNumber2",
                                "value"
                              ]).apply(null, eventArgs);

                              if (
                                eventArgs.length > 1 &&
                                eventArgs[1] &&
                                eventArgs[1]._plasmic_state_init_
                              ) {
                                return;
                              }
                            }}
                            placeholder={"6060606060"}
                          />
                        </FormItemWrapper>
                      </Stack__>
                      <FormItemWrapper
                        className={classNames(
                          "__wab_instance",
                          sty.formField__cAjBw
                        )}
                        label={"Adresse*"}
                        name={"address"}
                      >
                        <TextInput
                          data-plasmic-name={"rue"}
                          data-plasmic-override={overrides.rue}
                          className={classNames("__wab_instance", sty.rue)}
                          onChange={async (...eventArgs: any) => {
                            generateStateOnChangeProp($state, [
                              "rue",
                              "value"
                            ]).apply(null, eventArgs);

                            if (
                              eventArgs.length > 1 &&
                              eventArgs[1] &&
                              eventArgs[1]._plasmic_state_init_
                            ) {
                              return;
                            }
                          }}
                          placeholder={"Rue"}
                        />

                        <Stack__
                          as={"div"}
                          data-plasmic-name={"codePostalVille"}
                          data-plasmic-override={overrides.codePostalVille}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.codePostalVille
                          )}
                        >
                          <TextInput
                            data-plasmic-name={"codePostal"}
                            data-plasmic-override={overrides.codePostal}
                            className={classNames(
                              "__wab_instance",
                              sty.codePostal
                            )}
                            onChange={async (...eventArgs: any) => {
                              generateStateOnChangeProp($state, [
                                "codePostal",
                                "value"
                              ]).apply(null, eventArgs);

                              if (
                                eventArgs.length > 1 &&
                                eventArgs[1] &&
                                eventArgs[1]._plasmic_state_init_
                              ) {
                                return;
                              }
                            }}
                            placeholder={"Code postal"}
                          />

                          <Select
                            data-plasmic-name={"select"}
                            data-plasmic-override={overrides.select}
                            className={classNames("__wab_instance", sty.select)}
                            onChange={async (...eventArgs: any) => {
                              generateStateOnChangeProp($state, [
                                "select",
                                "value"
                              ]).apply(null, eventArgs);

                              if (
                                eventArgs.length > 1 &&
                                eventArgs[1] &&
                                eventArgs[1]._plasmic_state_init_
                              ) {
                                return;
                              }
                            }}
                            placeholder={"Ville"}
                            showLabel={false}
                          />
                        </Stack__>
                        <TextInput
                          data-plasmic-name={"pays"}
                          data-plasmic-override={overrides.pays}
                          className={classNames("__wab_instance", sty.pays)}
                          onChange={async (...eventArgs: any) => {
                            generateStateOnChangeProp($state, [
                              "pays",
                              "value"
                            ]).apply(null, eventArgs);

                            if (
                              eventArgs.length > 1 &&
                              eventArgs[1] &&
                              eventArgs[1]._plasmic_state_init_
                            ) {
                              return;
                            }
                          }}
                          placeholder={"Pays"}
                        />
                      </FormItemWrapper>
                      <FormItemWrapper
                        className={classNames(
                          "__wab_instance",
                          sty.formField___2RAap
                        )}
                        label={"Pr\u00e9sentation courte"}
                        name={"short_presentation"}
                      >
                        {(() => {
                          const child$Props = {
                            className: classNames(
                              "__wab_instance",
                              sty.textArea
                            ),
                            onChange: async (...eventArgs: any) => {
                              generateStateOnChangePropForCodeComponents(
                                $state,
                                "value",
                                ["textArea", "value"],
                                AntdTextArea_Helpers
                              ).apply(null, eventArgs);
                            },
                            placeholder: "Pr\u00e9sentation",
                            value: generateStateValueProp($state, [
                              "textArea",
                              "value"
                            ])
                          };
                          initializeCodeComponentStates(
                            $state,
                            [
                              {
                                name: "value",
                                plasmicStateName: "textArea.value"
                              }
                            ],
                            [],
                            AntdTextArea_Helpers ?? {},
                            child$Props
                          );

                          return (
                            <AntdTextArea
                              data-plasmic-name={"textArea"}
                              data-plasmic-override={overrides.textArea}
                              {...child$Props}
                            />
                          );
                        })()}
                      </FormItemWrapper>
                      <FormItemWrapper
                        className={classNames(
                          "__wab_instance",
                          sty.formField__vl74
                        )}
                        label={"Niveau d'exp\u00e9rience"}
                        name={"experience_level"}
                      >
                        <Select
                          data-plasmic-name={"niveauExperience"}
                          data-plasmic-override={overrides.niveauExperience}
                          className={classNames(
                            "__wab_instance",
                            sty.niveauExperience
                          )}
                          onChange={async (...eventArgs: any) => {
                            generateStateOnChangeProp($state, [
                              "niveauExperience",
                              "value"
                            ]).apply(null, eventArgs);

                            if (
                              eventArgs.length > 1 &&
                              eventArgs[1] &&
                              eventArgs[1]._plasmic_state_init_
                            ) {
                              return;
                            }
                          }}
                          placeholder={"S\u00e9l\u00e9ctionner"}
                          showLabel={false}
                        />
                      </FormItemWrapper>
                      <FormItemWrapper
                        className={classNames(
                          "__wab_instance",
                          sty.formField__vvnjx
                        )}
                        label={"Linkedin"}
                        name={"linkedin_url"}
                      >
                        <TextInput
                          data-plasmic-name={"textInput4"}
                          data-plasmic-override={overrides.textInput4}
                          className={classNames(
                            "__wab_instance",
                            sty.textInput4
                          )}
                          onChange={async (...eventArgs: any) => {
                            generateStateOnChangeProp($state, [
                              "textInput4",
                              "value"
                            ]).apply(null, eventArgs);

                            if (
                              eventArgs.length > 1 &&
                              eventArgs[1] &&
                              eventArgs[1]._plasmic_state_init_
                            ) {
                              return;
                            }
                          }}
                          placeholder={"https://"}
                        />
                      </FormItemWrapper>
                      <AntdButton
                        data-plasmic-name={"button"}
                        data-plasmic-override={overrides.button}
                        className={classNames("__wab_instance", sty.button)}
                        submitsForm={true}
                        type={"primary"}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___9JNbd
                          )}
                        >
                          {"Submit"}
                        </div>
                      </AntdButton>
                    </FormWrapper>
                  );
                })()}
              </div>
              <Stack__
                as={"div"}
                data-plasmic-name={"cvModificationDuMdp"}
                data-plasmic-override={overrides.cvModificationDuMdp}
                hasGap={true}
                className={classNames(projectcss.all, sty.cvModificationDuMdp)}
              >
                <div
                  data-plasmic-name={"frame1437254287"}
                  data-plasmic-override={overrides.frame1437254287}
                  className={classNames(projectcss.all, sty.frame1437254287)}
                >
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"card2"}
                    data-plasmic-override={overrides.card2}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.card2)}
                  >
                    <Stack__
                      as={"div"}
                      data-plasmic-name={"frame9"}
                      data-plasmic-override={overrides.frame9}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.frame9)}
                    >
                      <Stack__
                        as={"div"}
                        data-plasmic-name={"frame10"}
                        data-plasmic-override={overrides.frame10}
                        hasGap={true}
                        className={classNames(projectcss.all, sty.frame10)}
                      >
                        <div
                          data-plasmic-name={"email"}
                          data-plasmic-override={overrides.email}
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.email
                          )}
                        >
                          {"CV*"}
                        </div>
                        <Stack__
                          as={"div"}
                          data-plasmic-name={"fileUploader"}
                          data-plasmic-override={overrides.fileUploader}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.fileUploader
                          )}
                        >
                          <FileUploader
                            accept={"*/*"}
                            className={classNames(
                              "__wab_instance",
                              sty.fileUploader__qkD9J
                            )}
                            maxSize={5242880}
                            state={"default"}
                          />
                        </Stack__>
                      </Stack__>
                      <Stack__
                        as={"div"}
                        data-plasmic-name={"frame11"}
                        data-plasmic-override={overrides.frame11}
                        hasGap={true}
                        className={classNames(projectcss.all, sty.frame11)}
                      >
                        <div
                          data-plasmic-name={"email2"}
                          data-plasmic-override={overrides.email2}
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.email2
                          )}
                        >
                          {"Lettre de motivation"}
                        </div>
                        <Stack__
                          as={"div"}
                          data-plasmic-name={"fileUploader2"}
                          data-plasmic-override={overrides.fileUploader2}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.fileUploader2
                          )}
                        >
                          <FileUploader
                            accept={"*/*"}
                            className={classNames(
                              "__wab_instance",
                              sty.fileUploader__eU9Mf
                            )}
                            maxSize={5242880}
                            state={"default"}
                          />
                        </Stack__>
                      </Stack__>
                      <JamButton
                        className={classNames(
                          "__wab_instance",
                          sty.jamButton__z3S7G
                        )}
                        icon={"end"}
                        iconImage={
                          "/plasmic/jam_production_🚀/images/image11.svg"
                        }
                        label={"ENREGISTRER"}
                      />
                    </Stack__>
                  </Stack__>
                </div>
                <div
                  data-plasmic-name={"frame1437254288"}
                  data-plasmic-override={overrides.frame1437254288}
                  className={classNames(projectcss.all, sty.frame1437254288)}
                >
                  <div
                    data-plasmic-name={"freeBox"}
                    data-plasmic-override={overrides.freeBox}
                    className={classNames(projectcss.all, sty.freeBox)}
                  >
                    <Stack__
                      as={"div"}
                      data-plasmic-name={"card3"}
                      data-plasmic-override={overrides.card3}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.card3)}
                    >
                      {(() => {
                        const child$Props = {
                          className: classNames("__wab_instance", sty.form3),
                          extendedOnValuesChange: async (...eventArgs: any) => {
                            generateStateOnChangePropForCodeComponents(
                              $state,
                              "value",
                              ["form3", "value"],
                              FormWrapper_Helpers
                            ).apply(null, eventArgs);

                            (async (changedValues, allValues) => {
                              const $steps = {};

                              $steps["invokeGlobalAction"] = true
                                ? (() => {
                                    const actionArgs = {
                                      args: [
                                        (() => {
                                          try {
                                            return undefined;
                                          } catch (e) {
                                            if (
                                              e instanceof TypeError ||
                                              e?.plasmicType ===
                                                "PlasmicUndefinedDataError"
                                            ) {
                                              return undefined;
                                            }
                                            throw e;
                                          }
                                        })()
                                      ]
                                    };
                                    return $globalActions[
                                      "SupabaseUserGlobalContext.updateUserPassword"
                                    ]?.apply(null, [...actionArgs.args]);
                                  })()
                                : undefined;
                              if (
                                $steps["invokeGlobalAction"] != null &&
                                typeof $steps["invokeGlobalAction"] ===
                                  "object" &&
                                typeof $steps["invokeGlobalAction"].then ===
                                  "function"
                              ) {
                                $steps["invokeGlobalAction"] = await $steps[
                                  "invokeGlobalAction"
                                ];
                              }
                            }).apply(null, eventArgs);
                          },
                          formItems: [
                            { label: "Name", name: "name", inputType: "Text" },
                            {
                              label: "Message",
                              name: "message",
                              inputType: "Text Area"
                            }
                          ],
                          labelCol: { span: 8, horizontalOnly: true },
                          layout: "vertical",
                          mode: "advanced",
                          onFinish: async values => {
                            const $steps = {};

                            $steps["invokeGlobalAction"] = true
                              ? (() => {
                                  const actionArgs = {
                                    args: [
                                      (() => {
                                        try {
                                          return $state.mdp1;
                                        } catch (e) {
                                          if (
                                            e instanceof TypeError ||
                                            e?.plasmicType ===
                                              "PlasmicUndefinedDataError"
                                          ) {
                                            return undefined;
                                          }
                                          throw e;
                                        }
                                      })()
                                    ]
                                  };
                                  return $globalActions[
                                    "SupabaseUserGlobalContext.updateUserPassword"
                                  ]?.apply(null, [...actionArgs.args]);
                                })()
                              : undefined;
                            if (
                              $steps["invokeGlobalAction"] != null &&
                              typeof $steps["invokeGlobalAction"] ===
                                "object" &&
                              typeof $steps["invokeGlobalAction"].then ===
                                "function"
                            ) {
                              $steps["invokeGlobalAction"] = await $steps[
                                "invokeGlobalAction"
                              ];
                            }
                          },
                          onIsSubmittingChange: async (...eventArgs: any) => {
                            generateStateOnChangePropForCodeComponents(
                              $state,
                              "isSubmitting",
                              ["form3", "isSubmitting"],
                              FormWrapper_Helpers
                            ).apply(null, eventArgs);
                          },
                          ref: ref => {
                            $refs["form3"] = ref;
                          },
                          submitSlot: null,
                          wrapperCol: { span: 16, horizontalOnly: true }
                        };
                        initializeCodeComponentStates(
                          $state,
                          [
                            {
                              name: "value",
                              plasmicStateName: "form3.value"
                            },
                            {
                              name: "isSubmitting",
                              plasmicStateName: "form3.isSubmitting"
                            }
                          ],
                          [],
                          FormWrapper_Helpers ?? {},
                          child$Props
                        );

                        return (
                          <FormWrapper
                            data-plasmic-name={"form3"}
                            data-plasmic-override={overrides.form3}
                            {...child$Props}
                          >
                            <FormItemWrapper
                              className={classNames(
                                "__wab_instance",
                                sty.formField__vp2MG
                              )}
                              label={
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text__sb97T
                                  )}
                                >
                                  {"Inscription"}
                                </div>
                              }
                              name={"mdp1"}
                              noLabel={true}
                              rules={[
                                {
                                  ruleType: "advanced",
                                  custom: (rule, value) => {
                                    return (
                                      $state.password.match(
                                        /^(?=.*[A-Za-z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}$/
                                      ) !== null
                                    );
                                  },
                                  message:
                                    "Le mot de passe doit contenir au moins 8 caract\u00e8res, incluant des lettres, des chiffres et des symboles sp\u00e9ciaux."
                                }
                              ]}
                            >
                              <Stack__
                                as={"div"}
                                data-plasmic-name={"inputWrapper8"}
                                data-plasmic-override={overrides.inputWrapper8}
                                hasGap={true}
                                className={classNames(
                                  projectcss.all,
                                  sty.inputWrapper8
                                )}
                              >
                                <Stack__
                                  as={"div"}
                                  data-plasmic-name={"wrapper"}
                                  data-plasmic-override={overrides.wrapper}
                                  hasGap={true}
                                  className={classNames(
                                    projectcss.all,
                                    sty.wrapper
                                  )}
                                >
                                  <TextInput2
                                    data-plasmic-name={"textInput9"}
                                    data-plasmic-override={overrides.textInput9}
                                    className={classNames(
                                      "__wab_instance",
                                      sty.textInput9
                                    )}
                                    isMulti={false}
                                    label={"Modifier le mot de passe*"}
                                    placeholder={"**********"}
                                    showIcon={false}
                                    showLabel={true}
                                    state={"default"}
                                    text={""}
                                    type={"password"}
                                  />

                                  <Stack__
                                    as={"div"}
                                    data-plasmic-name={"wrapper2"}
                                    data-plasmic-override={overrides.wrapper2}
                                    hasGap={true}
                                    className={classNames(
                                      projectcss.all,
                                      sty.wrapper2
                                    )}
                                  >
                                    <Stack__
                                      as={"div"}
                                      data-plasmic-name={"progressBar"}
                                      data-plasmic-override={
                                        overrides.progressBar
                                      }
                                      hasGap={true}
                                      className={classNames(
                                        projectcss.all,
                                        sty.progressBar
                                      )}
                                    >
                                      {false ? (
                                        <div
                                          data-plasmic-name={
                                            "signedByBaseProgressBarSteppedMediumLabelNone"
                                          }
                                          data-plasmic-override={
                                            overrides.signedByBaseProgressBarSteppedMediumLabelNone
                                          }
                                          className={classNames(
                                            projectcss.all,
                                            sty.signedByBaseProgressBarSteppedMediumLabelNone
                                          )}
                                        />
                                      ) : null}
                                      {false ? (
                                        <div
                                          data-plasmic-name={"progress"}
                                          data-plasmic-override={
                                            overrides.progress
                                          }
                                          className={classNames(
                                            projectcss.all,
                                            sty.progress
                                          )}
                                        />
                                      ) : null}
                                      {false ? (
                                        <div
                                          data-plasmic-name={"inProgress"}
                                          data-plasmic-override={
                                            overrides.inProgress
                                          }
                                          className={classNames(
                                            projectcss.all,
                                            sty.inProgress
                                          )}
                                        />
                                      ) : null}
                                      <div
                                        data-plasmic-name={"base"}
                                        data-plasmic-override={overrides.base}
                                        className={classNames(
                                          projectcss.all,
                                          sty.base
                                        )}
                                      />

                                      <div
                                        data-plasmic-name={"base2"}
                                        data-plasmic-override={overrides.base2}
                                        className={classNames(
                                          projectcss.all,
                                          sty.base2
                                        )}
                                      />

                                      <div
                                        data-plasmic-name={"base3"}
                                        data-plasmic-override={overrides.base3}
                                        className={classNames(
                                          projectcss.all,
                                          sty.base3
                                        )}
                                      />

                                      <div
                                        data-plasmic-name={"base4"}
                                        data-plasmic-override={overrides.base4}
                                        className={classNames(
                                          projectcss.all,
                                          sty.base4
                                        )}
                                      />

                                      {false ? (
                                        <div
                                          data-plasmic-name={"base5"}
                                          data-plasmic-override={
                                            overrides.base5
                                          }
                                          className={classNames(
                                            projectcss.all,
                                            sty.base5
                                          )}
                                        />
                                      ) : null}
                                      {false ? (
                                        <div
                                          data-plasmic-name={"base6"}
                                          data-plasmic-override={
                                            overrides.base6
                                          }
                                          className={classNames(
                                            projectcss.all,
                                            sty.base6
                                          )}
                                        />
                                      ) : null}
                                    </Stack__>
                                    <div
                                      data-plasmic-name={"text"}
                                      data-plasmic-override={overrides.text}
                                      className={classNames(
                                        projectcss.all,
                                        projectcss.__wab_text,
                                        sty.text
                                      )}
                                    >
                                      {
                                        "Utilisez 8 caract\u00e8res ou plus en m\u00e9langeant lettres, chiffres et symboles."
                                      }
                                    </div>
                                  </Stack__>
                                </Stack__>
                              </Stack__>
                            </FormItemWrapper>
                            <FormItemWrapper
                              className={classNames(
                                "__wab_instance",
                                sty.formField__xhAzC
                              )}
                              label={
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text___14Zv
                                  )}
                                >
                                  {"Inscription"}
                                </div>
                              }
                              name={"mdp2"}
                              noLabel={true}
                              rules={[
                                {
                                  ruleType: "required",
                                  message:
                                    "La confirmation du mot de passe est requise."
                                },

                                {
                                  ruleType: "advanced",
                                  custom: (rule, value) => {
                                    return $state.password2 === $state.password;
                                  },
                                  message:
                                    "Les mots de passe ne correspondent pas."
                                }
                              ]}
                            >
                              <Stack__
                                as={"div"}
                                data-plasmic-name={"inputWrapper9"}
                                data-plasmic-override={overrides.inputWrapper9}
                                hasGap={true}
                                className={classNames(
                                  projectcss.all,
                                  sty.inputWrapper9
                                )}
                              >
                                <Stack__
                                  as={"div"}
                                  data-plasmic-name={"wrapper3"}
                                  data-plasmic-override={overrides.wrapper3}
                                  hasGap={true}
                                  className={classNames(
                                    projectcss.all,
                                    sty.wrapper3
                                  )}
                                >
                                  <TextInput2
                                    data-plasmic-name={"textInput10"}
                                    data-plasmic-override={
                                      overrides.textInput10
                                    }
                                    className={classNames(
                                      "__wab_instance",
                                      sty.textInput10
                                    )}
                                    isMulti={false}
                                    label={
                                      "R\u00e9p\u00e9tez le nouveau mot de passe*"
                                    }
                                    placeholder={"**********"}
                                    showIcon={false}
                                    showLabel={true}
                                    state={"default"}
                                    text={""}
                                    type={"password"}
                                  />
                                </Stack__>
                              </Stack__>
                            </FormItemWrapper>
                          </FormWrapper>
                        );
                      })()}
                      <JamButton
                        className={classNames(
                          "__wab_instance",
                          sty.jamButton__afT22
                        )}
                        icon={"end"}
                        iconImage={
                          "/plasmic/jam_production_🚀/images/image11.svg"
                        }
                        label={"ENREGISTRER"}
                        onClick={async () => {
                          const $steps = {};

                          $steps["runCode"] = true
                            ? (() => {
                                const actionArgs = {
                                  customFunction: async () => {
                                    return (() => {
                                      return ($state.form3.isSubmitting = true);
                                    })();
                                  }
                                };
                                return (({ customFunction }) => {
                                  return customFunction();
                                })?.apply(null, [actionArgs]);
                              })()
                            : undefined;
                          if (
                            $steps["runCode"] != null &&
                            typeof $steps["runCode"] === "object" &&
                            typeof $steps["runCode"].then === "function"
                          ) {
                            $steps["runCode"] = await $steps["runCode"];
                          }
                        }}
                      />
                    </Stack__>
                  </div>
                </div>
              </Stack__>
            </Stack__>
          </Stack__>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  parametresDeCompte: [
    "parametresDeCompte",
    "slidebar",
    "main",
    "title",
    "heading",
    "container",
    "informationsPersonnelles",
    "frame1437254343",
    "frame5",
    "frame6",
    "img",
    "editIcon",
    "frame7",
    "deleteIcon",
    "frame8",
    "tableCell",
    "text6",
    "textInputBase6",
    "hintText6",
    "formulaire",
    "prenomNom",
    "firstName",
    "lastName",
    "textInput3",
    "telephone",
    "phoneSelector",
    "phoneNumber2",
    "rue",
    "codePostalVille",
    "codePostal",
    "select",
    "pays",
    "textArea",
    "niveauExperience",
    "textInput4",
    "button",
    "cvModificationDuMdp",
    "frame1437254287",
    "card2",
    "frame9",
    "frame10",
    "email",
    "fileUploader",
    "frame11",
    "email2",
    "fileUploader2",
    "frame1437254288",
    "freeBox",
    "card3",
    "form3",
    "inputWrapper8",
    "wrapper",
    "textInput9",
    "wrapper2",
    "progressBar",
    "signedByBaseProgressBarSteppedMediumLabelNone",
    "progress",
    "inProgress",
    "base",
    "base2",
    "base3",
    "base4",
    "base5",
    "base6",
    "text",
    "inputWrapper9",
    "wrapper3",
    "textInput10"
  ],
  slidebar: ["slidebar"],
  main: [
    "main",
    "title",
    "heading",
    "container",
    "informationsPersonnelles",
    "frame1437254343",
    "frame5",
    "frame6",
    "img",
    "editIcon",
    "frame7",
    "deleteIcon",
    "frame8",
    "tableCell",
    "text6",
    "textInputBase6",
    "hintText6",
    "formulaire",
    "prenomNom",
    "firstName",
    "lastName",
    "textInput3",
    "telephone",
    "phoneSelector",
    "phoneNumber2",
    "rue",
    "codePostalVille",
    "codePostal",
    "select",
    "pays",
    "textArea",
    "niveauExperience",
    "textInput4",
    "button",
    "cvModificationDuMdp",
    "frame1437254287",
    "card2",
    "frame9",
    "frame10",
    "email",
    "fileUploader",
    "frame11",
    "email2",
    "fileUploader2",
    "frame1437254288",
    "freeBox",
    "card3",
    "form3",
    "inputWrapper8",
    "wrapper",
    "textInput9",
    "wrapper2",
    "progressBar",
    "signedByBaseProgressBarSteppedMediumLabelNone",
    "progress",
    "inProgress",
    "base",
    "base2",
    "base3",
    "base4",
    "base5",
    "base6",
    "text",
    "inputWrapper9",
    "wrapper3",
    "textInput10"
  ],
  title: ["title", "heading"],
  heading: ["heading"],
  container: [
    "container",
    "informationsPersonnelles",
    "frame1437254343",
    "frame5",
    "frame6",
    "img",
    "editIcon",
    "frame7",
    "deleteIcon",
    "frame8",
    "tableCell",
    "text6",
    "textInputBase6",
    "hintText6",
    "formulaire",
    "prenomNom",
    "firstName",
    "lastName",
    "textInput3",
    "telephone",
    "phoneSelector",
    "phoneNumber2",
    "rue",
    "codePostalVille",
    "codePostal",
    "select",
    "pays",
    "textArea",
    "niveauExperience",
    "textInput4",
    "button",
    "cvModificationDuMdp",
    "frame1437254287",
    "card2",
    "frame9",
    "frame10",
    "email",
    "fileUploader",
    "frame11",
    "email2",
    "fileUploader2",
    "frame1437254288",
    "freeBox",
    "card3",
    "form3",
    "inputWrapper8",
    "wrapper",
    "textInput9",
    "wrapper2",
    "progressBar",
    "signedByBaseProgressBarSteppedMediumLabelNone",
    "progress",
    "inProgress",
    "base",
    "base2",
    "base3",
    "base4",
    "base5",
    "base6",
    "text",
    "inputWrapper9",
    "wrapper3",
    "textInput10"
  ],
  informationsPersonnelles: [
    "informationsPersonnelles",
    "frame1437254343",
    "frame5",
    "frame6",
    "img",
    "editIcon",
    "frame7",
    "deleteIcon",
    "frame8",
    "tableCell",
    "text6",
    "textInputBase6",
    "hintText6",
    "formulaire",
    "prenomNom",
    "firstName",
    "lastName",
    "textInput3",
    "telephone",
    "phoneSelector",
    "phoneNumber2",
    "rue",
    "codePostalVille",
    "codePostal",
    "select",
    "pays",
    "textArea",
    "niveauExperience",
    "textInput4",
    "button"
  ],
  frame1437254343: [
    "frame1437254343",
    "frame5",
    "frame6",
    "img",
    "editIcon",
    "frame7",
    "deleteIcon",
    "frame8",
    "tableCell",
    "text6",
    "textInputBase6",
    "hintText6"
  ],
  frame5: [
    "frame5",
    "frame6",
    "img",
    "editIcon",
    "frame7",
    "deleteIcon",
    "frame8"
  ],
  frame6: ["frame6", "img"],
  img: ["img"],
  editIcon: ["editIcon", "frame7"],
  frame7: ["frame7"],
  deleteIcon: ["deleteIcon", "frame8"],
  frame8: ["frame8"],
  tableCell: ["tableCell", "text6"],
  text6: ["text6"],
  textInputBase6: ["textInputBase6", "hintText6"],
  hintText6: ["hintText6"],
  formulaire: [
    "formulaire",
    "prenomNom",
    "firstName",
    "lastName",
    "textInput3",
    "telephone",
    "phoneSelector",
    "phoneNumber2",
    "rue",
    "codePostalVille",
    "codePostal",
    "select",
    "pays",
    "textArea",
    "niveauExperience",
    "textInput4",
    "button"
  ],
  prenomNom: ["prenomNom", "firstName", "lastName"],
  firstName: ["firstName"],
  lastName: ["lastName"],
  textInput3: ["textInput3"],
  telephone: ["telephone", "phoneSelector", "phoneNumber2"],
  phoneSelector: ["phoneSelector"],
  phoneNumber2: ["phoneNumber2"],
  rue: ["rue"],
  codePostalVille: ["codePostalVille", "codePostal", "select"],
  codePostal: ["codePostal"],
  select: ["select"],
  pays: ["pays"],
  textArea: ["textArea"],
  niveauExperience: ["niveauExperience"],
  textInput4: ["textInput4"],
  button: ["button"],
  cvModificationDuMdp: [
    "cvModificationDuMdp",
    "frame1437254287",
    "card2",
    "frame9",
    "frame10",
    "email",
    "fileUploader",
    "frame11",
    "email2",
    "fileUploader2",
    "frame1437254288",
    "freeBox",
    "card3",
    "form3",
    "inputWrapper8",
    "wrapper",
    "textInput9",
    "wrapper2",
    "progressBar",
    "signedByBaseProgressBarSteppedMediumLabelNone",
    "progress",
    "inProgress",
    "base",
    "base2",
    "base3",
    "base4",
    "base5",
    "base6",
    "text",
    "inputWrapper9",
    "wrapper3",
    "textInput10"
  ],
  frame1437254287: [
    "frame1437254287",
    "card2",
    "frame9",
    "frame10",
    "email",
    "fileUploader",
    "frame11",
    "email2",
    "fileUploader2"
  ],
  card2: [
    "card2",
    "frame9",
    "frame10",
    "email",
    "fileUploader",
    "frame11",
    "email2",
    "fileUploader2"
  ],
  frame9: [
    "frame9",
    "frame10",
    "email",
    "fileUploader",
    "frame11",
    "email2",
    "fileUploader2"
  ],
  frame10: ["frame10", "email", "fileUploader"],
  email: ["email"],
  fileUploader: ["fileUploader"],
  frame11: ["frame11", "email2", "fileUploader2"],
  email2: ["email2"],
  fileUploader2: ["fileUploader2"],
  frame1437254288: [
    "frame1437254288",
    "freeBox",
    "card3",
    "form3",
    "inputWrapper8",
    "wrapper",
    "textInput9",
    "wrapper2",
    "progressBar",
    "signedByBaseProgressBarSteppedMediumLabelNone",
    "progress",
    "inProgress",
    "base",
    "base2",
    "base3",
    "base4",
    "base5",
    "base6",
    "text",
    "inputWrapper9",
    "wrapper3",
    "textInput10"
  ],
  freeBox: [
    "freeBox",
    "card3",
    "form3",
    "inputWrapper8",
    "wrapper",
    "textInput9",
    "wrapper2",
    "progressBar",
    "signedByBaseProgressBarSteppedMediumLabelNone",
    "progress",
    "inProgress",
    "base",
    "base2",
    "base3",
    "base4",
    "base5",
    "base6",
    "text",
    "inputWrapper9",
    "wrapper3",
    "textInput10"
  ],
  card3: [
    "card3",
    "form3",
    "inputWrapper8",
    "wrapper",
    "textInput9",
    "wrapper2",
    "progressBar",
    "signedByBaseProgressBarSteppedMediumLabelNone",
    "progress",
    "inProgress",
    "base",
    "base2",
    "base3",
    "base4",
    "base5",
    "base6",
    "text",
    "inputWrapper9",
    "wrapper3",
    "textInput10"
  ],
  form3: [
    "form3",
    "inputWrapper8",
    "wrapper",
    "textInput9",
    "wrapper2",
    "progressBar",
    "signedByBaseProgressBarSteppedMediumLabelNone",
    "progress",
    "inProgress",
    "base",
    "base2",
    "base3",
    "base4",
    "base5",
    "base6",
    "text",
    "inputWrapper9",
    "wrapper3",
    "textInput10"
  ],
  inputWrapper8: [
    "inputWrapper8",
    "wrapper",
    "textInput9",
    "wrapper2",
    "progressBar",
    "signedByBaseProgressBarSteppedMediumLabelNone",
    "progress",
    "inProgress",
    "base",
    "base2",
    "base3",
    "base4",
    "base5",
    "base6",
    "text"
  ],
  wrapper: [
    "wrapper",
    "textInput9",
    "wrapper2",
    "progressBar",
    "signedByBaseProgressBarSteppedMediumLabelNone",
    "progress",
    "inProgress",
    "base",
    "base2",
    "base3",
    "base4",
    "base5",
    "base6",
    "text"
  ],
  textInput9: ["textInput9"],
  wrapper2: [
    "wrapper2",
    "progressBar",
    "signedByBaseProgressBarSteppedMediumLabelNone",
    "progress",
    "inProgress",
    "base",
    "base2",
    "base3",
    "base4",
    "base5",
    "base6",
    "text"
  ],
  progressBar: [
    "progressBar",
    "signedByBaseProgressBarSteppedMediumLabelNone",
    "progress",
    "inProgress",
    "base",
    "base2",
    "base3",
    "base4",
    "base5",
    "base6"
  ],
  signedByBaseProgressBarSteppedMediumLabelNone: [
    "signedByBaseProgressBarSteppedMediumLabelNone"
  ],
  progress: ["progress"],
  inProgress: ["inProgress"],
  base: ["base"],
  base2: ["base2"],
  base3: ["base3"],
  base4: ["base4"],
  base5: ["base5"],
  base6: ["base6"],
  text: ["text"],
  inputWrapper9: ["inputWrapper9", "wrapper3", "textInput10"],
  wrapper3: ["wrapper3", "textInput10"],
  textInput10: ["textInput10"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  parametresDeCompte: "div";
  slidebar: typeof Slidebar;
  main: "main";
  title: "div";
  heading: "div";
  container: "div";
  informationsPersonnelles: "div";
  frame1437254343: "div";
  frame5: "div";
  frame6: "div";
  img: typeof PlasmicImg__;
  editIcon: "div";
  frame7: "div";
  deleteIcon: "div";
  frame8: "div";
  tableCell: "div";
  text6: "div";
  textInputBase6: "div";
  hintText6: "div";
  formulaire: typeof FormWrapper;
  prenomNom: "div";
  firstName: typeof TextInput;
  lastName: typeof TextInput;
  textInput3: typeof TextInput;
  telephone: "div";
  phoneSelector: typeof PhoneSelector;
  phoneNumber2: typeof TextInput;
  rue: typeof TextInput;
  codePostalVille: "div";
  codePostal: typeof TextInput;
  select: typeof Select;
  pays: typeof TextInput;
  textArea: typeof AntdTextArea;
  niveauExperience: typeof Select;
  textInput4: typeof TextInput;
  button: typeof AntdButton;
  cvModificationDuMdp: "div";
  frame1437254287: "div";
  card2: "div";
  frame9: "div";
  frame10: "div";
  email: "div";
  fileUploader: "div";
  frame11: "div";
  email2: "div";
  fileUploader2: "div";
  frame1437254288: "div";
  freeBox: "div";
  card3: "div";
  form3: typeof FormWrapper;
  inputWrapper8: "div";
  wrapper: "div";
  textInput9: typeof TextInput2;
  wrapper2: "div";
  progressBar: "div";
  signedByBaseProgressBarSteppedMediumLabelNone: "div";
  progress: "div";
  inProgress: "div";
  base: "div";
  base2: "div";
  base3: "div";
  base4: "div";
  base5: "div";
  base6: "div";
  text: "div";
  inputWrapper9: "div";
  wrapper3: "div";
  textInput10: typeof TextInput2;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicParametresDeCompte__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicParametresDeCompte__VariantsArgs;
    args?: PlasmicParametresDeCompte__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicParametresDeCompte__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicParametresDeCompte__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicParametresDeCompte__ArgProps,
          internalVariantPropNames: PlasmicParametresDeCompte__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicParametresDeCompte__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "parametresDeCompte") {
    func.displayName = "PlasmicParametresDeCompte";
  } else {
    func.displayName = `PlasmicParametresDeCompte.${nodeName}`;
  }
  return func;
}

export const PlasmicParametresDeCompte = Object.assign(
  // Top-level PlasmicParametresDeCompte renders the root element
  makeNodeComponent("parametresDeCompte"),
  {
    // Helper components rendering sub-elements
    slidebar: makeNodeComponent("slidebar"),
    main: makeNodeComponent("main"),
    title: makeNodeComponent("title"),
    heading: makeNodeComponent("heading"),
    container: makeNodeComponent("container"),
    informationsPersonnelles: makeNodeComponent("informationsPersonnelles"),
    frame1437254343: makeNodeComponent("frame1437254343"),
    frame5: makeNodeComponent("frame5"),
    frame6: makeNodeComponent("frame6"),
    img: makeNodeComponent("img"),
    editIcon: makeNodeComponent("editIcon"),
    frame7: makeNodeComponent("frame7"),
    deleteIcon: makeNodeComponent("deleteIcon"),
    frame8: makeNodeComponent("frame8"),
    tableCell: makeNodeComponent("tableCell"),
    text6: makeNodeComponent("text6"),
    textInputBase6: makeNodeComponent("textInputBase6"),
    hintText6: makeNodeComponent("hintText6"),
    formulaire: makeNodeComponent("formulaire"),
    prenomNom: makeNodeComponent("prenomNom"),
    firstName: makeNodeComponent("firstName"),
    lastName: makeNodeComponent("lastName"),
    textInput3: makeNodeComponent("textInput3"),
    telephone: makeNodeComponent("telephone"),
    phoneSelector: makeNodeComponent("phoneSelector"),
    phoneNumber2: makeNodeComponent("phoneNumber2"),
    rue: makeNodeComponent("rue"),
    codePostalVille: makeNodeComponent("codePostalVille"),
    codePostal: makeNodeComponent("codePostal"),
    select: makeNodeComponent("select"),
    pays: makeNodeComponent("pays"),
    textArea: makeNodeComponent("textArea"),
    niveauExperience: makeNodeComponent("niveauExperience"),
    textInput4: makeNodeComponent("textInput4"),
    button: makeNodeComponent("button"),
    cvModificationDuMdp: makeNodeComponent("cvModificationDuMdp"),
    frame1437254287: makeNodeComponent("frame1437254287"),
    card2: makeNodeComponent("card2"),
    frame9: makeNodeComponent("frame9"),
    frame10: makeNodeComponent("frame10"),
    email: makeNodeComponent("email"),
    fileUploader: makeNodeComponent("fileUploader"),
    frame11: makeNodeComponent("frame11"),
    email2: makeNodeComponent("email2"),
    fileUploader2: makeNodeComponent("fileUploader2"),
    frame1437254288: makeNodeComponent("frame1437254288"),
    freeBox: makeNodeComponent("freeBox"),
    card3: makeNodeComponent("card3"),
    form3: makeNodeComponent("form3"),
    inputWrapper8: makeNodeComponent("inputWrapper8"),
    wrapper: makeNodeComponent("wrapper"),
    textInput9: makeNodeComponent("textInput9"),
    wrapper2: makeNodeComponent("wrapper2"),
    progressBar: makeNodeComponent("progressBar"),
    signedByBaseProgressBarSteppedMediumLabelNone: makeNodeComponent(
      "signedByBaseProgressBarSteppedMediumLabelNone"
    ),
    progress: makeNodeComponent("progress"),
    inProgress: makeNodeComponent("inProgress"),
    base: makeNodeComponent("base"),
    base2: makeNodeComponent("base2"),
    base3: makeNodeComponent("base3"),
    base4: makeNodeComponent("base4"),
    base5: makeNodeComponent("base5"),
    base6: makeNodeComponent("base6"),
    text: makeNodeComponent("text"),
    inputWrapper9: makeNodeComponent("inputWrapper9"),
    wrapper3: makeNodeComponent("wrapper3"),
    textInput10: makeNodeComponent("textInput10"),

    // Metadata about props expected for PlasmicParametresDeCompte
    internalVariantProps: PlasmicParametresDeCompte__VariantProps,
    internalArgProps: PlasmicParametresDeCompte__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicParametresDeCompte;
/* prettier-ignore-end */
