/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: f7DE9y7qp46fyCw5nuY8f9
// Component: mm21s-vhdlTm

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { SignUp } from "../../../plasmic-library/authentication/SignUp"; // plasmic-import: l54x2CZo0bN2/codeComponent

import { useScreenVariants as useScreenVariantshm8Nko4B5BDd } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: HM8Nko4B5BDd/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_library_tailwind_3_4_number_tokens_css from "../library_tailwind_3_4_number_tokens/plasmic.module.css"; // plasmic-import: 4vjRXvnb4XuY6J15w9oRcQ/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: f7DE9y7qp46fyCw5nuY8f9/projectcss
import sty from "./PlasmicInscriptionEmployeur.module.css"; // plasmic-import: mm21s-vhdlTm/css

import PictogramIcon from "./icons/PlasmicIcon__Pictogram"; // plasmic-import: KlZQiGxQTluF/icon
import CheckIcon from "./icons/PlasmicIcon__Check"; // plasmic-import: wV32h4GpW1qw/icon

createPlasmicElementProxy;

export type PlasmicInscriptionEmployeur__VariantMembers = {};
export type PlasmicInscriptionEmployeur__VariantsArgs = {};
type VariantPropType = keyof PlasmicInscriptionEmployeur__VariantsArgs;
export const PlasmicInscriptionEmployeur__VariantProps =
  new Array<VariantPropType>();

export type PlasmicInscriptionEmployeur__ArgsType = {};
type ArgPropType = keyof PlasmicInscriptionEmployeur__ArgsType;
export const PlasmicInscriptionEmployeur__ArgProps = new Array<ArgPropType>();

export type PlasmicInscriptionEmployeur__OverridesType = {
  inscription?: Flex__<"div">;
  signUp?: Flex__<"div">;
  imageWrapper?: Flex__<"div">;
  logoWrapper?: Flex__<"div">;
  baseline?: Flex__<"div">;
  frame?: Flex__<"div">;
  frame2?: Flex__<"div">;
  frame3?: Flex__<"div">;
  formWrapper?: Flex__<"div">;
  signupLoading?: Flex__<"div">;
  signUp3?: Flex__<typeof SignUp>;
  signupSuccess?: Flex__<"div">;
  freeBox?: Flex__<"div">;
};

export interface DefaultInscriptionEmployeurProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicInscriptionEmployeur__RenderFunc(props: {
  variants: PlasmicInscriptionEmployeur__VariantsArgs;
  args: PlasmicInscriptionEmployeur__ArgsType;
  overrides: PlasmicInscriptionEmployeur__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const $globalActions = useGlobalActions?.();

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "signUp3.email",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => ""
      },
      {
        path: "signUp3.firstName",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => ""
      },
      {
        path: "signUp3.lastName",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => ""
      },
      {
        path: "signUp3.password",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => ""
      },
      {
        path: "signUp3.confirmPassword",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => ""
      },
      {
        path: "signUp3.phone",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => ""
      },
      {
        path: "signUp3.countryCode",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => "+33"
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantshm8Nko4B5BDd()
  });

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">
          {PlasmicInscriptionEmployeur.pageMetadata.title}
        </title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicInscriptionEmployeur.pageMetadata.title}
        />
        <meta
          key="twitter:title"
          name="twitter:title"
          content={PlasmicInscriptionEmployeur.pageMetadata.title}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"inscription"}
          data-plasmic-override={overrides.inscription}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            plasmic_library_tailwind_3_4_number_tokens_css.plasmic_tokens,
            plasmic_plasmic_rich_components_css.plasmic_tokens,
            sty.inscription
          )}
        >
          <div
            data-plasmic-name={"signUp"}
            data-plasmic-override={overrides.signUp}
            className={classNames(projectcss.all, sty.signUp)}
          >
            <Stack__
              as={"div"}
              data-plasmic-name={"imageWrapper"}
              data-plasmic-override={overrides.imageWrapper}
              hasGap={true}
              className={classNames(projectcss.all, sty.imageWrapper)}
            >
              <Stack__
                as={"div"}
                data-plasmic-name={"logoWrapper"}
                data-plasmic-override={overrides.logoWrapper}
                hasGap={true}
                className={classNames(projectcss.all, sty.logoWrapper)}
              >
                <PictogramIcon
                  className={classNames(projectcss.all, sty.svg___2Qx7)}
                  role={"img"}
                />

                <div
                  data-plasmic-name={"baseline"}
                  data-plasmic-override={overrides.baseline}
                  className={classNames(projectcss.all, sty.baseline)}
                >
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"frame"}
                    data-plasmic-override={overrides.frame}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.frame)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__jb0TE
                      )}
                    >
                      {"JOB"}
                    </div>
                  </Stack__>
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"frame2"}
                    data-plasmic-override={overrides.frame2}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.frame2)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__j7MKr
                      )}
                    >
                      {"AROUND"}
                    </div>
                  </Stack__>
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"frame3"}
                    data-plasmic-override={overrides.frame3}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.frame3)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__cx6D8
                      )}
                    >
                      {"ME"}
                    </div>
                  </Stack__>
                </div>
              </Stack__>
            </Stack__>
            <Stack__
              as={"div"}
              data-plasmic-name={"formWrapper"}
              data-plasmic-override={overrides.formWrapper}
              hasGap={true}
              className={classNames(projectcss.all, sty.formWrapper)}
            >
              {(() => {
                try {
                  return $ctx.query.signup !== "success";
                } catch (e) {
                  if (
                    e instanceof TypeError ||
                    e?.plasmicType === "PlasmicUndefinedDataError"
                  ) {
                    return true;
                  }
                  throw e;
                }
              })() ? (
                <div
                  data-plasmic-name={"signupLoading"}
                  data-plasmic-override={overrides.signupLoading}
                  className={classNames(projectcss.all, sty.signupLoading)}
                >
                  <SignUp
                    data-plasmic-name={"signUp3"}
                    data-plasmic-override={overrides.signUp3}
                    alertPosition={"top"}
                    appleButtonText={"APPLE"}
                    buttonAbordStyle={"tertiary"}
                    buttonStyle={"primary"}
                    className={classNames("__wab_instance", sty.signUp3)}
                    confirmPassword={generateStateValueProp($state, [
                      "signUp3",
                      "confirmPassword"
                    ])}
                    confirmPasswordLabel={"Répétez le mot de passe"}
                    countryCode={generateStateValueProp($state, [
                      "signUp3",
                      "countryCode"
                    ])}
                    email={generateStateValueProp($state, ["signUp3", "email"])}
                    emailLabel={"Email"}
                    eyeIconColor={"#666"}
                    firstName={generateStateValueProp($state, [
                      "signUp3",
                      "firstName"
                    ])}
                    firstNameLabel={"Prénom"}
                    googleButtonText={"GOOGLE"}
                    inputStyle={"simple"}
                    lastName={generateStateValueProp($state, [
                      "signUp3",
                      "lastName"
                    ])}
                    lastNameLabel={"Nom"}
                    maxAlerts={3}
                    oAuthButtonsPosition={"bottom"}
                    oAuthSeparatorText={"ou"}
                    onConfirmPasswordChange={async (...eventArgs: any) => {
                      generateStateOnChangeProp($state, [
                        "signUp3",
                        "confirmPassword"
                      ]).apply(null, eventArgs);
                    }}
                    onCountryCodeChange={async (...eventArgs: any) => {
                      generateStateOnChangeProp($state, [
                        "signUp3",
                        "countryCode"
                      ]).apply(null, eventArgs);
                    }}
                    onEmailChange={async (...eventArgs: any) => {
                      generateStateOnChangeProp($state, [
                        "signUp3",
                        "email"
                      ]).apply(null, eventArgs);
                    }}
                    onFirstNameChange={async (...eventArgs: any) => {
                      generateStateOnChangeProp($state, [
                        "signUp3",
                        "firstName"
                      ]).apply(null, eventArgs);
                    }}
                    onLastNameChange={async (...eventArgs: any) => {
                      generateStateOnChangeProp($state, [
                        "signUp3",
                        "lastName"
                      ]).apply(null, eventArgs);
                    }}
                    onPasswordChange={async (...eventArgs: any) => {
                      generateStateOnChangeProp($state, [
                        "signUp3",
                        "password"
                      ]).apply(null, eventArgs);
                    }}
                    onPhoneChange={async (...eventArgs: any) => {
                      generateStateOnChangeProp($state, [
                        "signUp3",
                        "phone"
                      ]).apply(null, eventArgs);
                    }}
                    onSubmit={async event => {
                      const $steps = {};

                      $steps["invokeGlobalAction"] = true
                        ? (() => {
                            const actionArgs = {
                              args: [
                                (() => {
                                  try {
                                    return $state.signUp3.email;
                                  } catch (e) {
                                    if (
                                      e instanceof TypeError ||
                                      e?.plasmicType ===
                                        "PlasmicUndefinedDataError"
                                    ) {
                                      return undefined;
                                    }
                                    throw e;
                                  }
                                })(),
                                (() => {
                                  try {
                                    return $state.signUp3.password;
                                  } catch (e) {
                                    if (
                                      e instanceof TypeError ||
                                      e?.plasmicType ===
                                        "PlasmicUndefinedDataError"
                                    ) {
                                      return undefined;
                                    }
                                    throw e;
                                  }
                                })(),
                                (() => {
                                  try {
                                    return "/register-company?signup=success";
                                  } catch (e) {
                                    if (
                                      e instanceof TypeError ||
                                      e?.plasmicType ===
                                        "PlasmicUndefinedDataError"
                                    ) {
                                      return undefined;
                                    }
                                    throw e;
                                  }
                                })(),
                                "/offre-employeur",
                                (() => {
                                  try {
                                    return {
                                      firstName: $state.signUp3.firstName,
                                      lastName: $state.signUp3.lastName,
                                      phone: $state.signUp3.phone,
                                      email: $state.signUp3.email,
                                      role: "Company"
                                    };
                                  } catch (e) {
                                    if (
                                      e instanceof TypeError ||
                                      e?.plasmicType ===
                                        "PlasmicUndefinedDataError"
                                    ) {
                                      return undefined;
                                    }
                                    throw e;
                                  }
                                })()
                              ]
                            };
                            return $globalActions[
                              "SupabaseUserGlobalContext.signup"
                            ]?.apply(null, [...actionArgs.args]);
                          })()
                        : undefined;
                      if (
                        $steps["invokeGlobalAction"] != null &&
                        typeof $steps["invokeGlobalAction"] === "object" &&
                        typeof $steps["invokeGlobalAction"].then === "function"
                      ) {
                        $steps["invokeGlobalAction"] = await $steps[
                          "invokeGlobalAction"
                        ];
                      }
                    }}
                    padding={"40px 16px"}
                    password={generateStateValueProp($state, [
                      "signUp3",
                      "password"
                    ])}
                    passwordInfoText={
                      "Utilisez 8 caractères ou plus en mélangeant lettres, chiffres et symboles."
                    }
                    passwordLabel={"Mot de passe"}
                    passwordStrength={true}
                    phone={generateStateValueProp($state, ["signUp3", "phone"])}
                    phoneLabel={"Téléphone"}
                    placeholderConfirmPassword={"Confirmez votre mot de passe"}
                    placeholderEmail={"Entrez votre email"}
                    placeholderPassword={"Entrez votre mot de passe"}
                    placeholderPhone={"060606060606"}
                    privacyPolicyText={
                      "J'accepte la politique de confidentialité"
                    }
                    redirectAfterSignUp={"/"}
                    showAlerts={true}
                    showLabels={true}
                    showLoginLink={true}
                    showOAuthButtons={false}
                    showPasswordToggle={true}
                    showPhoneInput={true}
                    submitButtonText={"S'inscrire"}
                    title={"Bienvenue !"}
                    titleHeading={"h1"}
                    wrapperStyle={"card"}
                  />
                </div>
              ) : null}
              {(() => {
                try {
                  return $ctx.query.signup === "success";
                } catch (e) {
                  if (
                    e instanceof TypeError ||
                    e?.plasmicType === "PlasmicUndefinedDataError"
                  ) {
                    return true;
                  }
                  throw e;
                }
              })() ? (
                <Stack__
                  as={"div"}
                  data-plasmic-name={"signupSuccess"}
                  data-plasmic-override={overrides.signupSuccess}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.signupSuccess)}
                >
                  <CheckIcon
                    className={classNames(projectcss.all, sty.svg__coecU)}
                    role={"img"}
                  />

                  <Stack__
                    as={"div"}
                    data-plasmic-name={"freeBox"}
                    data-plasmic-override={overrides.freeBox}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___3U5N6
                      )}
                    >
                      {
                        "Votre compte a \u00e9t\u00e9 cr\u00e9\u00e9 avec succ\u00e8s"
                      }
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___3UfL
                      )}
                    >
                      {
                        "Veuillez v\u00e9rifier vos e-mails pour confirmer votre adresse \net acc\u00e9der \u00e0 Job Around Me."
                      }
                    </div>
                  </Stack__>
                </Stack__>
              ) : null}
            </Stack__>
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  inscription: [
    "inscription",
    "signUp",
    "imageWrapper",
    "logoWrapper",
    "baseline",
    "frame",
    "frame2",
    "frame3",
    "formWrapper",
    "signupLoading",
    "signUp3",
    "signupSuccess",
    "freeBox"
  ],
  signUp: [
    "signUp",
    "imageWrapper",
    "logoWrapper",
    "baseline",
    "frame",
    "frame2",
    "frame3",
    "formWrapper",
    "signupLoading",
    "signUp3",
    "signupSuccess",
    "freeBox"
  ],
  imageWrapper: [
    "imageWrapper",
    "logoWrapper",
    "baseline",
    "frame",
    "frame2",
    "frame3"
  ],
  logoWrapper: ["logoWrapper", "baseline", "frame", "frame2", "frame3"],
  baseline: ["baseline", "frame", "frame2", "frame3"],
  frame: ["frame"],
  frame2: ["frame2"],
  frame3: ["frame3"],
  formWrapper: [
    "formWrapper",
    "signupLoading",
    "signUp3",
    "signupSuccess",
    "freeBox"
  ],
  signupLoading: ["signupLoading", "signUp3"],
  signUp3: ["signUp3"],
  signupSuccess: ["signupSuccess", "freeBox"],
  freeBox: ["freeBox"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  inscription: "div";
  signUp: "div";
  imageWrapper: "div";
  logoWrapper: "div";
  baseline: "div";
  frame: "div";
  frame2: "div";
  frame3: "div";
  formWrapper: "div";
  signupLoading: "div";
  signUp3: typeof SignUp;
  signupSuccess: "div";
  freeBox: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicInscriptionEmployeur__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicInscriptionEmployeur__VariantsArgs;
    args?: PlasmicInscriptionEmployeur__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicInscriptionEmployeur__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicInscriptionEmployeur__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicInscriptionEmployeur__ArgProps,
          internalVariantPropNames: PlasmicInscriptionEmployeur__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicInscriptionEmployeur__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "inscription") {
    func.displayName = "PlasmicInscriptionEmployeur";
  } else {
    func.displayName = `PlasmicInscriptionEmployeur.${nodeName}`;
  }
  return func;
}

export const PlasmicInscriptionEmployeur = Object.assign(
  // Top-level PlasmicInscriptionEmployeur renders the root element
  makeNodeComponent("inscription"),
  {
    // Helper components rendering sub-elements
    signUp: makeNodeComponent("signUp"),
    imageWrapper: makeNodeComponent("imageWrapper"),
    logoWrapper: makeNodeComponent("logoWrapper"),
    baseline: makeNodeComponent("baseline"),
    frame: makeNodeComponent("frame"),
    frame2: makeNodeComponent("frame2"),
    frame3: makeNodeComponent("frame3"),
    formWrapper: makeNodeComponent("formWrapper"),
    signupLoading: makeNodeComponent("signupLoading"),
    signUp3: makeNodeComponent("signUp3"),
    signupSuccess: makeNodeComponent("signupSuccess"),
    freeBox: makeNodeComponent("freeBox"),

    // Metadata about props expected for PlasmicInscriptionEmployeur
    internalVariantProps: PlasmicInscriptionEmployeur__VariantProps,
    internalArgProps: PlasmicInscriptionEmployeur__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "Inscription",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicInscriptionEmployeur;
/* prettier-ignore-end */
